import { Chapter } from './types';

export const ch1: Chapter = {
  id: 1,
  name: "Arjuna Vishada Yoga",
  meaning: "The Yoga of Arjuna's Dejection",
  slokas_count: 47,
  summary: "The battle of Kurukshetra is about to begin. Arjuna, seeing his relatives and teachers on the opposing side, is overwhelmed by grief and refuses to fight, seeking Krishna's counsel.",
  themes: ["Crisis of Identity", "Moral Dilemma", "Attachment", "The Human Condition"],
  featured_verse: "1.1",
  slokas: [
    { verse: "1.1", sanskrit: "धृतराष्ट्र उवाच |\nधर्मक्षेत्रे कुरुक्षेत्रे समवेता युयुत्सवः |\nमामकाः पाण्डवाश्चैव किमकुर्वत सञ्जय ||", transliteration: "dhṛitarāśhtra uvācha |\ndharma-kṣhetre kuru-kṣhetre samavetā yuyutsavaḥ |\nmāmakāḥ pāṇḍavāśhchaiva kimakurvata sañjaya ||", meaning: "Dhritarashtra said: O Sanjaya, gathered on the holy field of Kurukshetra, desiring to fight, what did my sons and the sons of Pandu do?", lesson: "Recognize that your mind is a battlefield. Constantly evaluate if your actions are driven by wisdom (Pandavas) or selfish ego (Kauravas)." },
    { verse: "1.2", sanskrit: "सञ्जय उवाच |\nदृष्ट्वा तु पाण्डवानीकं व्यूढं दुर्योधनस्तदा |\nआचार्यमुपसङ्गम्य राजा वचनमब्रवीत् ||", transliteration: "sañjaya uvācha |\ndṛiṣhṭvā tu pāṇḍavānīkaṁ vyūḍhaṁ duryodhanas tadā |\nāchāryam upasaṅgamya rājā vachanam abravīt ||", meaning: "Sanjaya said: Upon seeing the Pandava army arrayed in battle formation, King Duryodhana approached his teacher and spoke these words.", lesson: "When faced with challenges, even the powerful seek reassurance. Observe how anxiety often precedes action." },
    { verse: "1.3", sanskrit: "पश्यैतां पाण्डुपुत्राणामाचार्य महतीं चमूम् |\nव्यूढां द्रुपदपुत्रेण तव शिष्येण धीमता ||", transliteration: "paśhyaitāṁ pāṇḍu-putrāṇām āchārya mahatīṁ chamūm |\nvyūḍhāṁ drupada-putreṇa tava śhiṣhyeṇa dhīmatā ||", meaning: "Behold, O teacher, the mighty army of the sons of Pandu, so expertly arrayed by your intelligent disciple, the son of Drupada.", lesson: "Respect the competence of your opposition. Realism is the first requirement of strategy." },
    { verse: "1.10", sanskrit: "अपर्याप्तं तदस्माकं बलं भीष्माभिरक्षितम् |\nपर्याप्तं त्विदमेतेषां बलं भीमाभिरक्षितम् ||", transliteration: "aparyāptaṁ tad asmākaṁ balaṁ bhīṣhmābhirakṣhitam |\nparyāptaṁ tvid am eteṣhāṁ balaṁ bhīmābhirakṣhitam ||", meaning: "Our strength is unlimited and we are well-protected by Grandfather Bhishma, while the strength of the Pandavas, protected by Bhima, is limited.", lesson: "Overconfidence and external assessment of strength can be deceptive. True power lies in internal conviction and righteousness." },
    { verse: "1.20", sanskrit: "अथ व्यवस्थितान्दृष्ट्वा धार्तराष्ट्रान् कपिध्वजः |\nप्रवृत्ते शस्त्रसम्पाते धनुरुद्यम्य पाण्डवः ||", transliteration: "atha vyavasthitān dṛiṣhṭvā dhārtarāṣhṭrān kapi-dhvajaḥ |\npravṛitte śhastra-sampāte dhanur udyamya pāṇḍavaḥ ||", meaning: "Then, seeing the sons of Dhritarashtra arrayed against him and the war-missiles about to be released, Arjuna, whose flag bore the image of Hanuman, took up his bow.", lesson: "Preparation for duty. Even when emotionally conflicted, one must maintain the physical readiness to perform one's role." },
    { verse: "1.21", sanskrit: "अर्जुन उवाच |\nसेनयोरुभयोर्मध्ये रथं स्थापय मेऽच्युत ||", transliteration: "arjuna uvācha |\nsenayor ubhayor madhye rathaṁ sthāpaya me ’chyuta ||", meaning: "Arjuna said: O Infallible One, please place my chariot between the two armies.", lesson: "Objectivity. To make clear decisions, one must step back and observe the situation from a neutral, balanced perspective." },
    { verse: "1.23", sanskrit: "योत्स्यमानानवेक्षेऽहं य एतेऽत्र समागताः |\nधार्तराष्ट्रस्य दुर्बुद्धेर्युद्धे प्रियचिकीर्षवः ||", transliteration: "yotsyamānān avekṣhe ’haṁ ya ete ’tra samāgatāḥ |\ndhārtarāṣhṭrasya durbuddher yuddhe priya-chikīrṣhavaḥ ||", meaning: "Let me look upon those who have come here to fight, desiring to please the evil-minded son of Dhritarashtra in this war.", lesson: "Analyze the motives. Understand not just what people are doing, but whose interests they are serving." },
    { verse: "1.26", sanskrit: "तत्रापश्यत्स्थितान् पार्थः पितृनथ पितामहान् |\nआचार्यान्मातुलान्भ्रातृन्पुत्रान्पौत्रान्सखींस्तथा ||", transliteration: "tatrāpaśhyat sthitān pārthaḥ pitṛīn atha pitāmahān |\nāchāryān mātulān bhrātṛīn putrān pautrān sakhīṁs tathā ||", meaning: "There Arjuna saw his fathers, grandfathers, teachers, maternal uncles, brothers, sons, grandsons, and friends.", lesson: "The reality of conflict. Often, our hardest duties involve confronting those we love or the habits we are most attached to." },
    { verse: "1.28", sanskrit: "अर्जुन उवाच |\nदृष्ट्वेमं स्वजनं कृष्ण युयुत्सुं समुपस्थितम् |\nसीदन्ति मम गात्राणि मुखं च परिशुष्यति ||", transliteration: "arjuna uvācha |\ndṛiṣhṭvemaṁ swa-janaṁ kṛiṣhṇa yuyutsuṁ samupasthitam |\nsīdanti mama gātrāṇi mukhaṁ cha pariśhuṣhyati ||", meaning: "Arjuna said: My dear Krishna, seeing my friends and relatives present before me in such a fighting spirit, I feel the limbs of my body quivering and my mouth drying up.", lesson: "Emotional paralysis. Acknowledge when attachment is clouding your ability to act. This is the first step toward seeking wisdom." },
    { verse: "1.30", sanskrit: "गाण्डीवं स्रंसते हस्तात्त्वक्चैव परिदह्यते |\nन च शक्नोम्यवस्थातुं भ्रमतीव च मे मनः ||", transliteration: "gāṇḍīvaṁ sraṁsate hastāt tvak chaiva paridahyate |\nna cha śhaknomy avasthātuṁ bhramatīva cha me manaḥ ||", meaning: "My bow Gandiva is slipping from my hand, and my skin is burning. I am unable to stand steady any longer, and my mind is reeling.", lesson: "The physical weight of mental stress. Our environment and tools become useless when our internal state is in chaos." },
    { verse: "1.31", sanskrit: "निमित्तानि च पश्यामि विपरीतानि केशव |\nन च श्रेयोऽनुपश्यामि हत्वा स्वजनमाहवे ||", transliteration: "nimittāni cha paśhyāmi viparītāni keśhava |\nna cha śhreyo ’nupaśhyāmi hatvā swa-janam āhave ||", meaning: "I see only inauspicious omens, O Krishna. I cannot see how any good can come from killing my own kinsmen in this battle.", lesson: "Distorted perception. When we are overwhelmed by emotion, we tend to see only the negatives and ignore our actual responsibilities." },
    { verse: "1.35", sanskrit: "एतान्न हन्तुमिच्छामि घ्नतोऽपि मधुसूदन |\nअपि त्रैलोक्यराज्यस्य हेतोः किं नु महीकृते ||", transliteration: "etān na hantum ichchhāmi ghnato ’pi madhusūdana |\napi trailokya-rājyasya hetoḥ kiṁ nu mahī-kṛite ||", meaning: "O Madhusudana, I do not wish to kill them, even though they may kill me. I would not want to fight them even for the sovereignty of the three worlds, what to speak of this earth?", lesson: "Questioning the cost of success. Is the external prize worth the internal betrayal of one's values?" },
    { verse: "1.36", sanskrit: "पापमेवाश्रयेदस्मान्हत्वैतानाततायिनः |\nतस्मान्नार्हा वयं हन्तुं धार्तराष्ट्रान्स्वबान्धवान् ||", transliteration: "pāpam evāśhrayed asmān hatvaitān ātatāyinaḥ |\ntasmān nārhā vayaṁ hantuṁ dhārtarāṣhṭrān swa-bāndhavān ||", meaning: "Sin will take hold of us if we kill these aggressors. Therefore, it is not proper for us to kill the sons of Dhritarashtra, our own cousins.", lesson: "Moral confusion. Arjuna uses spiritual logic to justify his emotional weakness. We often do the same to avoid difficult tasks." },
    { verse: "1.40", sanskrit: "कुलक्षये प्रणश्यन्ति कुलधर्माः सनातनाः |\nधर्मे नष्टे कुलं कृत्स्नमधर्मोऽभिभवत्युत ||", transliteration: "kula-kṣhaye praṇaśhyanti kula-dharmāḥ sanātanāḥ |\ndharme naṣhṭe kulaṁ kṛitsnam adharmo ’bhibhavaty uta ||", meaning: "With the destruction of the family, the eternal family traditions perish; and when traditions are lost, the whole family becomes involved in irreligion.", lesson: "Long-term consequences. Arjuna is right to worry about the social impact of war, but he is missing the immediate cosmic necessity of justice." },
    { verse: "1.44", sanskrit: "अहो बत महत्पापं कर्तुं व्यवसिता वयम् |\nयद्राज्यसुखलोभेन हन्तुं स्वजनमुद्यताः ||", transliteration: "aho bata mahat pāpaṁ kartuṁ vyavasitā vayam |\nyad rājya-sukha-lobhena hantuṁ swa-janam udyatāḥ ||", meaning: "Alas! How strange it is that we are preparing to commit a great sin, driven by the desire to enjoy royal happiness, by being ready to kill our own kinsmen.", lesson: "Self-Reflection. Arjuna is honest about his greed for power, which is a rare and noble trait even in his confused state." },
    { verse: "1.45", sanskrit: "यदि मामप्रतीकारमशस्त्रं शस्त्रपाणयः |\nधार्तराष्ट्रा रणे हन्युस्तन्मे क्षेमतरं भवेत् ||", transliteration: "yadi mām apratīkāram aśhastraṁ śhastra-pāṇayaḥ |\ndhārtarāṣhṭrā raṇe hanyus tan me kṣhemataraṁ bhavet ||", meaning: "It would be better for me if the sons of Dhritarashtra, weapons in hand, were to kill me unarmed and unresisting on the battlefield.", lesson: "Despair. This represents the total collapse of the will. It is often the 'rock bottom' needed before a spiritual awakening can begin." },
    { verse: "1.47", sanskrit: "सञ्जय उवाच |\nएवमुक्त्वार्जुनः संख्ये रथोपस्थ उपाविशत् |\nविसृज्य सशरं चापं शोकसंविग्नमानसः ||", transliteration: "sañjaya uvācha |\nevam uktvārjunaḥ saṅkhye rathopastha upāviśhat |\nvisṛijya sa-śharaṁ chāpaṁ śhoka-saṁvigna-mānasaḥ ||", meaning: "Sanjaya said: Having spoken thus, Arjuna cast aside his bow and arrows and sat down on the chariot, his mind overwhelmed with grief.", lesson: "Surrender to the Guru. Arjuna's total helplessness is the necessary condition for Krishna to begin the discourse of the Gita." }
  ]
};