import { Chapter } from './types';

export const ch10: Chapter = {
  id: 10,
  name: "Vibhuti-Vistara-Yoga",
  meaning: "The Yoga of Manifested Opulence",
  slokas_count: 42,
  summary: "Krishna describes His infinite manifestations and splendors in the world, helping Arjuna to see the Divine in all excellence and beauty.",
  themes: ["Divine Majesty", "Awe", "Greatness in All Things", "Reflection"],
  featured_verse: "10.41",
  slokas: [
    { verse: "10.1", sanskrit: "श्रीभगवानुवाच |\nभूय एव महाबाहो शृणु मे परमं वचः |\nयत्तेऽहं प्रीयमाणाय वक्ष्यामि हितकाम्यया ||", transliteration: "śhrī-bhagavān uvācha |\nbhūya eva mahā-bāho śhṛiṇu me paramaṁ vachaḥ |\nyat te ’haṁ prīyamāṇāya vakṣhyāmi hita-kāmyayā ||", meaning: "The Supreme Lord said: My dear friend, O mighty-armed Arjuna, listen again to My supreme word, which I shall impart to you for your benefit and which will give you great joy.", lesson: "Ongoing Guidance. True wisdom is a dialogue. Stay open to new insights as you grow." },
    { verse: "10.2", sanskrit: "न मे विदुः सुरगणाः प्रभवं न महर्षयः |\nअहमादिर्हि देवानां महर्षीणां च सर्वशः ||", transliteration: "na me viduḥ sura-gaṇāḥ prabhavaṁ na maharṣhayaḥ |\naham ādir hi devānāṁ maharṣhīṇāṁ cha sarvaśhaḥ ||", meaning: "Neither the hosts of demigods nor the great sages know My origin or opulences, for, in every respect, I am the source of the demigods and sages.", lesson: "The Infinite. Recognize that the source of reality is beyond any labels or history. It is the 'Pre-history' of everything." },
    { verse: "10.4", sanskrit: "बुद्धिर्ज्ञानमसंमोहः क्षमा सत्यं दमः शमः |\nसुखं दुःखं भवोऽभावो भयं चाभयमेव च ||", transliteration: "buddhir jñānam asammohaḥ kṣhamā satyaṁ damaḥ śhamaḥ |\nsukhaṁ duḥkhaṁ bhavo ’bhāvo bhayaṁ chābhayam eva cha ||", meaning: "Intelligence, knowledge, freedom from doubt and delusion, forgiveness, truthfulness, control of the senses, control of the mind, happiness and distress, birth, death, fear, fearlessness...", lesson: "Mental States as Divine Gifts. Even your ability to forgive or be brave is a spark of the Divine working through you. Value these traits." },
    { verse: "10.8", sanskrit: "अहं सर्वस्य प्रभवो मत्तः सर्वं प्रवर्तते |\nइति मत्वा भजन्ते मां बुधा भावसमन्विताः ||", transliteration: "ahaṁ sarvasya prabhavo mattaḥ sarvaṁ pravartate |\niti matvā bhajante māṁ budhā bhāva-samanvitāḥ ||", meaning: "I am the source of all spiritual and material worlds. Everything emanates from Me. The wise who perfectly know this engage in My devotional service and worship Me with all their hearts.", lesson: "Universal Source. When you see the Source in everything, your life becomes a constant state of reverence." },
    { verse: "10.9", sanskrit: "मच्चित्ता मद्गतप्राणा बोधयन्तः परस्परम् |\nकथयन्तश्च मां नित्यं तुष्यन्ति च रमन्ति च ||", transliteration: "mach-chittā mad-gata-prāṇā bodhayantaḥ parasparam |\nkathayantaśh cha māṁ nityaṁ tuṣhyanti cha ramanti ch ||", meaning: "The thoughts of My pure devotees dwell in Me, their lives are fully devoted to My service, and they derive great satisfaction and bliss from always enlightening one another and conversing about Me.", lesson: "Spiritual Community. Finding joy in shared wisdom is one of the highest pleasures available to humans." },
    { verse: "10.10", sanskrit: "तेषां सततयुक्तानां भजतां प्रीतिपूर्वकम् |\nददामि बुद्धियोगं तं येन मामुपयान्ति ते ||", transliteration: "teṣhāṁ satata-yuktāṇāṁ bhajatāṁ prīti-pūrvakam |\ndadāmi buddhi-yogaṁ taṁ yena mām upayānti te ||", meaning: "To those who are constantly devoted to serving Me with love, I give the understanding by which they can come to Me.", lesson: "The Gift of Intuition. Sincere love opens up the 'eyes' of the intellect. God guides you from within when your heart is pure." },
    { verse: "10.11", sanskrit: "तेषामेवानुकम्पार्थमहमज्ञानजं तमः |\nनाशयाम्यात्मभावस्थो ज्ञानदीपेन भास्वता ||", transliteration: "teṣhām evānukampārtham aham ajñāna-jaṁ tamaḥ |\nnāśhayāmy ātma-bhāva-stho jñāna-dīpena bhāswatā ||", meaning: "To show them special mercy, I, dwelling in their hearts, destroy with the shining lamp of knowledge the darkness born of ignorance.", lesson: "Inner Light. You don't have to fight darkness; just turn on the light. Wisdom is the lamp that dispels all fear." },
    { verse: "10.20", sanskrit: "अहमात्मा गुडाकेश सर्वभूताशयस्थितः |\nअहमादिश्च मध्यं च भूतानामन्त एव च ||", transliteration: "aham ātmā guḍākeśha sarva-bhūtāśhaya-sthitaḥ |\naham ādiśh cha madhyaṁ cha bhūtānām anta eva cha ||", meaning: "I am the Soul, O Arjuna, seated in the hearts of all living entities. I am the beginning, the middle and the end of all beings.", lesson: "The Resident Guide. God is closer to you than your own breath. Trust the quiet voice in your heart." },
    { verse: "10.22", sanskrit: "वेदानां सामवेदोऽस्मि देवानामस्मि वासवः |\nइन्द्रियाणां मनश्चास्मि भूतानामस्मि चेतना ||", transliteration: "vedānāṁ sāma-vedo ’smi devānām asmi vāsavaḥ |\nindriyāṇāṁ manaśh chāsmi bhūtānām asmi chetanā ||", meaning: "Of the Vedas I am the Sama Veda; of the demigods I am Indra, the king of heaven; of the senses I am the mind; and in living beings I am the living force [consciousness].", lesson: "Essence. Whenever you see the 'best' or 'most powerful' version of anything, recognize it as a divine manifestation." },
    { verse: "10.30", sanskrit: "प्रह्लादश्चास्मि दैत्यानां कालः कलयतामहम् |\nमृगाणां च मृगेन्द्रोऽहं वैनतेयश्च पक्षिणाम् ||", transliteration: "prahlādaśh chāsmi daityānāṁ kālaḥ kalayatām aham |\nmṛigāṇāṁ cha mṛigendro ’haṁ vainateyaśh cha pakṣhiṇām ||", meaning: "Among the Daitya demons I am the devoted Prahlada, among subduers I am time, among beasts I am the lion, and among birds I am Garuda.", lesson: "Divine Persistence. Even in the midst of 'demonic' or difficult environments, a spark of pure devotion (like Prahlada) is always possible." },
    { verse: "10.33", sanskrit: "अक्षराणामकारोऽस्मि द्वन्द्वः सामासिकस्य च |\nअहमेवाक्षयः कालो धाताहं विश्वतोमुखः ||", transliteration: "akṣharāṇām akāro ’smi dvandvaḥ sāmāsikasya cha |\naham evākṣhayaḥ kālo dhātāhaṁ viśhwato-mukhaḥ ||", meaning: "Of letters I am the letter A, and among compound word functions I am the dual. I am also inexhaustible time, and of creators I am Brahma.", lesson: "Foundations. Recognize the Divine in the simplest building blocks of life—like the letters of the alphabet or the passage of time." },
    { verse: "10.36", sanskrit: "द्यूतं छलयतामस्मि तेजस्तेजस्विनामहम् |\nजयोऽस्मि व्यवसायोऽस्मि सत्त्वं सत्त्ववतामहम् ||", transliteration: "dyūtaṁ chhalayatām asmi tejas tejasvinām aham |\njayo ’smi vyavasāyo ’smi sattvaṁ sattvavatām aham ||", meaning: "I am the gambling of cheats, and of the splendid I am the splendor. I am victory, I am adventure, and I am the strength of the strong.", lesson: "Pervasive Power. God is in the 'Splendor' and the 'Victory'. Even the ability to compete or achieve is a divine energy borrowed for a moment." },
    { verse: "10.39", sanskrit: "यच्चापि सर्वभूतानां बीजं तदहमर्जुन |\nन तदस्ति विना यत्स्यान्मया भूतं चराचरम् ||", transliteration: "yach chāpi sarva-bhūtānāṁ bījaṁ tad aham arjuna |\nna tad asti vinā yat syān mayā bhūtaṁ charācharam ||", meaning: "Furthermore, O Arjuna, I am the generating seed of all existences. There is no being—moving or unmoving—that can exist without Me.", lesson: "Fundamental Dependency. Everything you see relies on a deeper life force. Humility comes from realizing we are not the creators, just the stewards." },
    { verse: "10.41", sanskrit: "यद्यद्विभूतिमत्सत्त्वं श्रीमदूर्जितमेव वा |\nतत्तदेवावगच्छ त्वं मम तेजोंऽशसम्भवम् ||", transliteration: "yad yad vibhūtimat sattvaṁ śhrīmad ūrjitam eva vā |\ntat tad evāvagachchha tvaṁ mama tejo-’nśha-sambhavam ||", meaning: "Know that whatever is powerful, beautiful, or glorious in this world is but a spark of My splendor.", lesson: "Appreciate Beauty Properly. When you see talent or beauty, don't just admire the person; admire the Source that lent them that spark." },
    { verse: "10.42", sanskrit: "अथवा बहुनैतेन किं ज्ञातेन तवार्जुन |\nविष्टभ्याहमिदं कृत्स्नमेकांशेन स्थितो जगत् ||", transliteration: "atha vā bahunaitena kiṁ jñātena tavārjuna |\nviṣhṭabhyāham idaṁ kṛitsnam ekāṁśhena sthito jagat ||", meaning: "But what need is there, Arjuna, for all this detailed knowledge? With a single fragment of Myself I pervade and support this entire universe.", lesson: "The Infinite Scale. As grand as the world is, it is just a tiny fraction of the ultimate Reality. Stay humble in the face of the Infinite." }
  ]
};