
import { Chapter } from './types';

export const ch11: Chapter = {
  id: 11,
  name: "Vishwaroopa-Darshana Yoga",
  meaning: "The Yoga of Universal Form",
  slokas_count: 55,
  summary: "At Arjuna's request, Krishna reveals His awesome Universal Form, containing the entire cosmos, past, present, and future.",
  themes: ["Cosmic Vision", "Time the Destroyer", "Total Surrender", "Awe"],
  featured_verse: "11.32",
  slokas: [
    { verse: "11.1", sanskrit: "अर्जुन उवाच |\nमदनुग्रहाय परमं गुह्यमध्यात्मसंज्ञितम् |\nयत्त्वयोक्तं वचस्तेन मोहोऽयं विगतो मम ||", transliteration: "arjuna uvācha |\nmad-anugrahāya paramaṁ guhyam adhyātma-sañjñitam |\nyat tvayoktaṁ vachas tena moho ’yaṁ vigato mama ||", meaning: "Arjuna said: Out of compassion for me, You have revealed the most confidential spiritual knowledge. By hearing Your words, my delusion has been dispelled.", lesson: "The power of hearing Truth. Divine knowledge is a medicine that cures the confusion of the ego." },
    { verse: "11.8", sanskrit: "न तु मां शक्यसे द्रष्टुमनेनैव स्वचक्षुषा |\nदिव्यं ददामि ते चक्षुः पश्य मे योगमैश्वरम् ||", transliteration: "na tu māṁ śhakyase draṣhṭum anenaiva swa-chakṣhuṣhā |\ndivyaṁ dadāmi te chakṣhuḥ paśhya me yogam aiśhwaram ||", meaning: "But you cannot see Me with your present eyes. Therefore I give you divine sight. Behold My mystic opulence!", lesson: "Divine Vision. To see the deeper reality of the universe, we must upgrade our 'lenses' from physical to spiritual." },
    { verse: "11.12", sanskrit: "दिवि सूर्यसहस्रस्य भवेद्युगपदुत्थिता |\nयदि भाः सदृशी सा स्याद्भासस्तस्य महात्मनः ||", transliteration: "divi sūrya-sahasrasya bhavedyugapad utthitā |\nyadi bhāḥ sadṛiśhī sā syād bhāsas tasya mahātmanaḥ ||", meaning: "If a thousand suns were to blaze forth all at once in the sky, their brilliance might resemble that of the Supreme Lord in that universal form.", lesson: "The Divine is beyond imagination. Our human language and senses can only hint at the overwhelming majesty of Reality." },
    { verse: "11.15", sanskrit: "अर्जुन उवाच |\nपश्यामि देवांस्तव देव देहे\nसर्वांस्तथा भूतविशेषसङ्घान् |\nब्रह्माणमीशं कमलासनस्थ\nमृषींश्च सर्वानुरगांश्च दिव्यान् ||", transliteration: "arjuna uvācha |\npaśhyāmi devāns tava deva dehe\nsarvāns tathā bhūta-viśheṣha-saṅghān |\nbrahmāṇam īśhaṁ kamalāsana-stham\nṛiṣhīṅśh cha sarvān uragāṅśh cha divyān ||", meaning: "Arjuna said: O Lord, I see within Your body all the gods and various other living entities. I see Brahma seated on the lotus flower, as well as Lord Shiva and all the sages and divine serpents.", lesson: "Unity in the One. Everything in existence—the high, the low, the sacred, and the mundane—is part of the same Divine Body." },
    { verse: "11.32", sanskrit: "कालोऽस्मि लोकक्षयकृत्प्रवृद्धो\nलोकान्समाहर्तुमिह प्रवृत्तः |\nऋतेऽपि त्वां न भविष्यन्ति सर्वे\nयेऽवस्थिताः प्रत्यनीकेषु योधाः ||", transliteration: "kālo ’smi loka-kṣhaya-kṛit pravṛiddho |\nlokān samāhartum iha pravṛittaḥ ||", meaning: "I am Time, the mighty destroyer of worlds, out to annihilate everyone. Even without your participation, all these warriors shall be slain.", lesson: "The Inevitability of Time. Align yourself with the Divine will, knowing that the larger script of life is already written." },
    { verse: "11.33", sanskrit: "तस्मात्त्वमुत्तिष्ठ यशो लभस्व\nजित्वा शत्रून्भुङ्क्ष्व राज्यं समृद्धम् |\nमयैवैते निहताः पूर्वमेव\nनिमित्तमात्रं भव सव्यसाचिन् ||", transliteration: "tasmāt tvam uttiṣhṭha yaśho labhaswa\njitvā śhatrūn bhuṅkṣhva rājyaṁ samṛiddham |\nmayaitāni nihatāḥ pūrvam eva\nnimitta-mātraṁ bhava savya-sāchin ||", meaning: "Therefore, arise! Win glory, conquer your enemies, and enjoy a prosperous kingdom. They are already slain by Me; be but an instrument in my hands, O Arjuna.", lesson: "Be an instrument. Your job is to show up and do your best; the outcome is managed by a much larger power." },
    { verse: "11.36", sanskrit: "सञ्जय उवाच |\nस्थाने हृषीकेश तव प्रकीर्त्या\nजगत्प्रहृष्यत्यनु रज्यते च |\nरक्षांसि भीतानि दिशो द्रवन्ति\nसर्वे नमस्यन्ति च सिद्धसङ्घाः ||", transliteration: "sañjaya uvācha |\nsthāne hṛiṣhīkeśha tava prakīrtyā\njagat prahṛiṣhyaty anu rajyate cha |\nrakṣhāṅsi bhītāni diśho dravanti\nsarve namasyanti cha siddha-saṅghāḥ ||", meaning: "Sanjaya said: O Hrishikesha, the world rejoices at Your fame and becomes attached to You. The demons fly in fear in all directions, while all the perfected beings bow down to You.", lesson: "The Vibration of Truth. Living in alignment with the Divine brings joy to the righteous and dispels the 'demons' of fear and ego." },
    { verse: "11.40", sanskrit: "नमः पुरस्तादथ पृष्ठतस्ते\nनमोऽस्तु ते सर्वत एव सर्व |\nअनन्तवीर्यामितविक्रमस्त्वं\nसर्वं समाप्नोषि ततोऽसि सर्वः ||", transliteration: "namaḥ purastād atha pṛiṣhṭhatas te\nnamo ’stu te sarvata eva sarva |\nananta-vīryāmita-vikramas tvaṁ\nsarvaṁ samāpnoṣhi tato ’si sarvaḥ ||", meaning: "Salutations to You from the front and from behind! Salutations to You from all sides! O All-pervading One, You possess infinite power and boundless might. You pervade everything, and thus You are everything.", lesson: "Omnipresence. God is not just 'out there'; He is behind you, in front of you, and within you at all times." },
    { verse: "11.43", sanskrit: "पितासि लोकस्य चराचरस्य\nत्वमस्य पूज्यश्च गुरुर्गरीयान् |\nन त्वत्समोऽस्त्यभ्यधिकः कुतोऽन्यो\nलोकत्रयेऽप्यप्रतिमप्रभाव ||", transliteration: "pitāsi lokasya charācharasya\ntvam asya pūjyaśh cha gurur garīyān |\nna tvat-samo ’sty abhyadhikaḥ kuto ’nyo\nloka-traye ’py apratima-prabhāva ||", meaning: "You are the Father of the whole world, of all that is moving and unmoving. You are the most adorable Teacher and the greatest Guru. No one is equal to You in the three worlds, O Being of incomparable power!", lesson: "The Ultimate Guide. When we look for mentorship, the Divine is the supreme source of wisdom and support." },
    { verse: "11.44", sanskrit: "तस्मात्प्रणम्य प्रणिधाय कायं\nप्रसादये त्वामहमीशमीड्यम् |\nपितेव पुत्रस्य सखेव सख्युः\nप्रियः प्रियायार्हसि देव सोढुम् ||", transliteration: "tasmāt praṇamya praṇidhāya kāyaṁ\nprasādaye tvām aham īśham īḍyam |\npiteva putrasya sakheva sakhyuḥ\npriyaḥ priyāyārhasi deva soḍhum ||", meaning: "Therefore, bowing down and prostrating my body, I seek Your grace, O adorable Lord. As a father forgives his son, a friend his friend, or a lover his beloved, please forgive me, O God.", lesson: "Intimacy with the Divine. We can relate to the Supreme in many ways—as a parent, a friend, or a lover. This relationship is built on trust and forgiveness." },
    { verse: "11.47", sanskrit: "श्रीभगवानुवाच |\nमया प्रसन्नेन तवार्जुनेदं\nरूपं परं दर्शितमात्मयोगात् |\nतेजोमयं विश्वमनन्तमाद्यं\nयन्मे त्वदन्येन न दृष्टपूर्वम् ||", transliteration: "śhrī-bhagavān uvācha |\nmayā prasannena tavārjunedaṁ\nrūpaṁ paraṁ darśhitam ātma-yogāt |\ntejo-mayaṁ viśhwam anantam ādyaṁ\nyan me tvad-anyena na dṛiṣhṭa-pūrvam ||", meaning: "The Supreme Lord said: My dear Arjuna, happily have I shown you, by My internal potency, this supreme universal form within the material world. No one before you has ever seen this unlimited, primeval form, full of glaring effulgence.", lesson: "Grace is required for Vision. Hard work is necessary, but the final 'unveiling' of Truth is a gift from the Divine." },
    { verse: "11.50", sanskrit: "सञ्जय उवाच |\nइत्यर्जुनं वासुदेवस्तथोक्त्वा\nस्वकं रूपं दर्शयामास भूयः |\nआश्वासयामास च भीतमेनं\nभूत्वा पुनः सौम्यवपुर्महात्मा ||", transliteration: "sañjaya uvācha |\nity arjunaṁ vāsudevas tathoktvā\nswakaṁ rūpaṁ darśhayām āsa bhūyaḥ |\nāśhwāsayām āsa cha bhītam enaṁ\nbhūtvā punaḥ saumya-vapur mahātmā ||", meaning: "Sanjaya said: Having spoken thus to Arjuna, Krishna showed him His own four-armed form and at last His two-armed form, thus encouraging the fearful Arjuna.", lesson: "Return to Form. The vastness of the universe can be frightening; the Personal form of God provides comfort and a point of focus for the human heart." },
    { verse: "11.53", sanskrit: "नाहं वेदैर्न तपसा न दानेन न चेज्यया |\nशक्य एवंविधो द्रष्टुं दृष्टवानसि मां यथा ||", transliteration: "nāhaṁ vedair na tapasā na dānena na chejyayā |\nśhakya evaṁ-vidho draṣhṭuṁ dṛiṣhṭavān asi māṁ yathā ||", meaning: "The form you are seeing Me in cannot be understood simply by studying the Vedas, nor by performing penances, nor by charity, nor by worship.", lesson: "Beyond Ritual. Spiritual 'credits' are good, but they don't automatically grant the highest realization. Something more is needed." },
    { verse: "11.54", sanskrit: "भक्त्या त्वनन्यया शक्य अहमेवंविधोऽर्जुन |\nज्ञातुं द्रष्टुं च तत्त्वेन प्रवेष्टुं च परन्तप ||", transliteration: "bhaktyā tv ananyayā śhakya aham evaṁ-vidho ’rjuna |\njñātuṁ draṣhṭuṁ cha tattvena praveṣṭuṁ cha parantapa ||", meaning: "My dear Arjuna, only by undivided devotional service can I be understood as I am, standing before you, and can thus be seen directly. Only in this way can you enter into the mysteries of My understanding.", lesson: "Love is the Key. Undivided love (Bhakti) is the only frequency that truly connects the human soul to the Divine heart." },
    { verse: "11.55", sanskrit: "मत्कर्मकृन्मत्परमो मद्भक्तः सङ्गवर्जितः |\nनिर्वैरः सर्वभूतेषु यः स मामेति पाण्डव ||", transliteration: "mat-karma-kṛin mat-paramo mad-bhaktaḥ saṅga-varjitaḥ |\nnirvairaḥ sarva-bhūteṣhu yaḥ sa mām eti pāṇḍava ||", meaning: "Those who perform all their duties for My sake, who make Me their supreme goal, who are devoted to Me, free from attachment, and without enmity toward any living being, come to Me.", lesson: "The Complete Formula. Duty + Divine Goal + Love + Detachment + Universal Kindness = Liberation." }
  ]
};
