
import { Chapter } from './types';

export const ch12: Chapter = {
  id: 12,
  name: "Bhakti Yoga",
  meaning: "The Yoga of Devotion",
  slokas_count: 20,
  summary: "Krishna describes the path of devotion and lists the qualities that make a devotee dear to Him. He emphasizes that while both the unmanifest and manifest paths lead to Him, the path of the manifest (Personal God) is easier for embodied beings.",
  themes: ["Love for God", "Compassion", "Emotional Stability", "Inner Purity", "Devotional Service"],
  featured_verse: "12.13",
  slokas: [
    { verse: "12.1", sanskrit: "अर्जुन उवाच |\nएवं सततयुक्ता ये भक्तास्त्वां पर्युपासते |\nये चाप्यक्षरमव्यक्तं तेषां के योगवित्तमाः ||", transliteration: "arjuna uvācha |\nevaṁ satata-yuktā ye bhaktās tvāṁ paryupāsate |\nye chāpy akṣharam avyaktaṁ teṣhāṁ ke yoga-vittamāḥ ||", meaning: "Arjuna asked: Between those who are always united with You in devotion and those who worship the unmanifested, imperishable Absolute, who are considered more perfect in Yoga?", lesson: "Sincere inquiry is the path to clarity. Never hesitate to ask for the most efficient path to your spiritual goals." },
    { verse: "12.2", sanskrit: "श्रीभगवानुवाच |\nमय्यावेश्य मनो ये मां नित्ययुक्ता उपासते |\nश्रद्धया परयोपेतास्ते मे युक्ततमा मताः ||", transliteration: "śhrī-bhagavān uvācha |\nmayy āveśhya mano ye māṁ nitya-yuktā upāsate |\nśhraddhayā parayopetās te me yuktatamā matāḥ ||", meaning: "The Supreme Lord said: Those who fix their minds on Me and always engage in My worship with steadfast and supreme faith are considered by Me to be the most perfect in Yoga.", lesson: "Focus and Faith. The quality of your attention determines the depth of your connection to the Divine." },
    { verse: "12.3", sanskrit: "ये त्वक्षरमनिर्देश्यमव्यक्तं पर्युपासते |\nसर्वत्रगमचिन्त्यं च कूटस्थमचलं ध्रुवम् ||", transliteration: "ye tv akṣharam anirdeśhyam avyaktaṁ paryupāsate |\nsarvatra-gam achintyaṁ cha kūṭa-stham achalaṁ dhruvam ||", meaning: "But those who worship the imperishable, the indefinable, the unmanifest, the omnipresent, the unthinkable, the unchanging, the immovable, and the eternal...", lesson: "Truth has many facets. The formless Absolute is real, but requires immense mental strength to conceptualize." },
    { verse: "12.4", sanskrit: "संनियम्येन्द्रियग्रामं सर्वत्र समबुद्धयः |\nते प्राप्नुवन्ति मामेव सर्वभूतहिते रताः ||", transliteration: "sanniyamyendriya-grāmaṁ sarvatra sama-buddhayaḥ |\nte prāpnuvanti mām eva sarva-bhūta-hite ratāḥ ||", meaning: "...by controlling the senses, being even-minded everywhere, and being engaged in the welfare of all beings, they also attain Me.", lesson: "Service to humanity is service to God. Purity of heart and universal kindness are prerequisites for any spiritual path." },
    { verse: "12.5", sanskrit: "क्लेशोऽधिकतरस्तेषामव्यक्तासक्तचेतसाम् |\nअव्यक्ता हि गतिर्दुःखं देहवद्भिरवाप्यते ||", transliteration: "kleśho ’dhikataras teṣhām avyaktāsakta-chetasām |\navyaktā hi gatir duḥkhaṁ dehavadbhir avāpyate ||", meaning: "For those whose minds are attached to the unmanifest, the struggle is greater; for the path of the unmanifest is difficult for embodied beings to attain.", lesson: "Work with your nature, not against it. As beings with bodies, connecting with a personal form of the Divine is often more natural and joyful." },
    { verse: "12.6", sanskrit: "ये तु सर्वाणि कर्माणि मयि संन्यस्य मत्पराः |\nअनन्येनैव योगेन मां ध्यायन्त उपासते ||", transliteration: "ye tu sarvāṇi karmāṇi mayi sannyasya mat-parāḥ |\nananyenaiva yogena māṁ dhyāyanta upāsate ||", meaning: "But those who surrender all their actions to Me, regarding Me as the Supreme, and meditate on Me with exclusive devotion...", lesson: "Total surrender simplifies life. When every act is an offering, every moment becomes sacred." },
    { verse: "12.7", sanskrit: "तेषामहं समुद्धर्ता मृत्युसंसारसागरात् |\nभवामि नचिरात्पार्थ मय्यावेशितचेतसाम् ||", transliteration: "teṣhām ahaṁ samuddhartā mṛityu-saṁsāra-sāgarāt |\nbhavāmi nachirāt pārtha mayy āveśhita-chetasām ||", meaning: "I quickly become the deliverer from the ocean of birth and death for those whose minds are fixed on Me, O Parth.", lesson: "You are not alone in your journey. The Divine reaches out to those who reach out to Him." },
    { verse: "12.8", sanskrit: "मय्येव मन आधत्स्व मयि बुद्धिं निवेशय |\nनिवसिष्यसि मय्येव अत ऊर्ध्वं न संशयः ||", transliteration: "mayyeva mana ādhatswa mayi buddhiṁ niveśhaya |\nnivasiṣhyasi mayyeva ata ūrdhvaṁ na sanśhayaḥ ||", meaning: "Fix your mind on Me alone and surrender your intellect to Me. Thereon, you will always live in Me, without a doubt.", lesson: "Home is within. When your thoughts and intelligence are anchored in Truth, you reside in a state of eternal peace." },
    { verse: "12.9", sanskrit: "अथ चित्तं समाधातुं न शक्नोषि मयि स्थिरम् |\nअभ्यासयोगेन ततो मामिच्छाप्तुं धनञ्जय ||", transliteration: "atha chittaṁ samādhātuṁ na śhaknoṣhi mayi sthiram |\nabhyāsa-yogena tato mām ichchhāptuṁ dhanañjaya ||", meaning: "If you are unable to fix your mind steadily on Me, then seek to reach Me by the practice of repeating Yoga (Abhyasa-yoga), O Dhananjaya.", lesson: "Persistence is the key. If you fail to focus today, try again tomorrow. Spiritual growth is a series of small, consistent efforts." },
    { verse: "12.10", sanskrit: "अभ्यासेऽप्यसमर्थोऽसि मत्कर्मपरमो भव |\nमदर्थमपि कर्माणि कुर्वन्सिद्धिमवाप्स्यसि ||", transliteration: "abhyāse ’py asamartho ’si mat-karma-peramo bhava |\nmad-artham api karmāṇi kurvan siddhim avāpsyasi ||", meaning: "If you cannot even practice this, then be intent on performing actions for My sake. By working for Me, you will also attain perfection.", lesson: "Action as prayer. Even if you cannot meditate, you can act with the intention of serving the higher good." },
    { verse: "12.11", sanskrit: "अथैतदप्यशक्तोऽसि कर्तुं मद्योगमाश्रितः |\nसर्वकर्मफलत्यागं ततः कुरु यतात्मवान् ||", transliteration: "athaitad apy aśhakto ’si kartuṁ mad-yogam āśhritaḥ |\nsarva-karma-phala-tyāgaṁ tataḥ kuru yatātmavān ||", meaning: "If you are unable even to do this, then, taking refuge in My Yoga, renounce the fruits of all your actions with self-control.", lesson: "The final safety net. If all else fails, simply do your duty and let go of the result. Detachment brings immediate peace." },
    { verse: "12.12", sanskrit: "श्रेयो हि ज्ञानमभ्यासाज्ज्ञानाद्ध्यानं विशिष्यते |\nध्यानात्कर्मफलत्यागस्त्यागाच्छान्तिरनन्तरम् ||", transliteration: "śhreyo hi jñānam abhyāsāj jñānād dhyānaṁ viśhiṣhyate |\ndhyānāt karma-phala-tyāgas tyāgāch chhāntir anantaram ||", meaning: "Knowledge is better than mere practice; meditation is better than knowledge; and renunciation of the fruits of action is better than meditation, for peace follows such renunciation.", lesson: "The hierarchy of peace. Relinquishing the ego's demand for specific outcomes is the most direct path to tranquility." },
    { verse: "12.13", sanskrit: "अद्वेष्टा सर्वभूतानां मैत्रः करुण एव च |\nनिर्ममो निरहङ्कारः समदुःखसुखः क्षमी ||", transliteration: "adveṣhṭā sarva-bhūtāṇāṁ maitraḥ karuṇa eva cha |\nnirmamo nirahankāraḥ sama-duḥkha-sukhaḥ kṣhamī ||", meaning: "Those who do not hate any living being, who are friendly and compassionate to all, who are free from possessiveness and ego, even-minded in pleasure and pain, and forgiving...", lesson: "The marks of a saint. Cultivate kindness, humility, and equanimity as your primary spiritual tools." },
    { verse: "12.14", sanskrit: "सन्तुष्टः सततं योगी यतात्मा दृढनिश्चयः |\nमय्यर्पितमनोबुद्धिर्यो मे भक्तः स मे प्रियः ||", transliteration: "santuṣhṭaḥ satataṁ yogī yatātmā dṛiḍha-niśhchayaḥ |\nmayy arpita-mano-buddhir yo me bhaktaḥ sa me priyaḥ ||", meaning: "...who are always contented, yogic, self-controlled, of firm resolve, with mind and intellect surrendered to Me—such devotees are very dear to Me.", lesson: "Contentment is power. When you are happy with what you have and focused on your path, you become a magnet for divine grace." },
    { verse: "12.15", sanskrit: "यस्मान्नोद्विजते लोको लोकान्नोद्विजते च यः |\nहर्षामर्षभयोद्वेगैर्मुक्तो यः स च मे प्रियः ||", transliteration: "yasmān nodvijate loko lokān nodvijate cha yaḥ |\nharṣhāmarṣha-bhayodvegair mukto yaḥ sa cha me priyaḥ ||", meaning: "Those by whom the world is not agitated and who are not agitated by the world, who are free from joy, envy, fear, and anxiety—they are very dear to Me.", lesson: "Emotional independence. Aim to be someone who brings peace to others and remains peaceful regardless of external drama." },
    { verse: "12.16", sanskrit: "अनपेक्षः शुचिर्दक्ष उदासीनो गतव्यथः |\nसर्वारम्भपरित्यागी यो मे भक्तः स मे प्रियः ||", transliteration: "anapekṣhaḥ śhuchir dakṣha udāsīno gata-vyathaḥ |\nsarvārambha-parityāgī yo me bhaktaḥ sa me priyaḥ ||", meaning: "Those who are indifferent to worldly gain, pure, expert, unconcerned, untroubled, and who have renounced all sense of doership in their undertakings—such devotees are dear to Me.", lesson: "Excellence without attachment. Be expert in your work (daksha) but remain mentally free from its outcomes." },
    { verse: "12.17", sanskrit: "यो न हृष्यति न द्वेष्टि न शोचति न काङ्क्षति |\nशुभाशुभपरित्यागी भक्तिमान्यः स मे प्रियः ||", transliteration: "yo na hṛiṣhyati na dveṣhṭi na śhochati na kāṅkṣhati |\nśhubhāśhuba-parityāgī bhaktimān yaḥ sa me priyaḥ ||", meaning: "Those who neither rejoice nor hate, neither grieve nor desire, and who renounce both auspicious and inauspicious outcomes—such persons, full of devotion, are dear to Me.", lesson: "Equilibrium. True devotion transcends the binary of 'good' and 'bad' luck, seeing the divine hand in everything." },
    { verse: "12.18", sanskrit: "समः शत्रौ च मित्रे च तथा मानापमानयोः |\nशीतोष्णसुखदुःखेषु समः सङ्गविवर्जितः ||", transliteration: "samaḥ śhatrau cha mitre cha tathā mānāpamānayoḥ |\nśhītoṣhṇa-sukha-duḥkheṣhu samaḥ saṅga-vivarjitaḥ ||", meaning: "Those who are alike to friend and foe, even-minded in honor and dishonor, cold and heat, pleasure and pain, and free from all attachment...", lesson: "Internal consistency. Your peace should not depend on how others treat you or what the environment is like." },
    { verse: "12.19", sanskrit: "तुल्यनिन्दास्तुतिर्मौनी सन्तुष्टो येन केनचित् |\nअनिकेतः स्थिरमतिर्भक्तिमान्मे प्रियो नरः ||", transliteration: "tulya-nindā-stutir maunī santuṣhṭo yena kenachit |\naniketaḥ sthira-matir bhaktimān me priyo naraḥ ||", meaning: "...who take praise and blame with equanimity, who are silent (contemplative), content with whatever comes their way, without a permanent home (unattached), and of steady mind—such devotees are dear to Me.", lesson: "The power of silence and steady mind. Don't be swayed by the opinions of the world; stay anchored in your inner truth." },
    { verse: "12.20", sanskrit: "ये तु धर्म्यामृतमिदं यथोक्तं पर्युपासते |\nश्रद्दधाना मत्परमा भक्तास्तेऽतीव मे प्रियाः ||", transliteration: "ye tu dharmyāmṛitam idaṁ yathoktaṁ paryupāsate |\nśhraddadhānā mat-paramā bhaktās te ’tīva me priyāḥ ||", meaning: "Those who follow this nectar of Dharma as described above, endowed with faith and regarding Me as their supreme goal, such devotees are exceedingly dear to Me.", lesson: "The final promise. Living the values of Bhakti Yoga leads to the highest state of love and proximity to the Divine." }
  ]
};
