import { Chapter } from './types';

export const ch13: Chapter = {
  id: 13,
  name: "Kshetra-Kshetrajna Yoga",
  meaning: "The Yoga of the Field and the Knower",
  slokas_count: 34,
  summary: "Krishna explains the difference between the physical body (the field), the soul (the knower), and the Supreme Soul who knows all fields.",
  themes: ["Discernment", "Nature of Reality", "Consciousness", "Body vs Soul"],
  featured_verse: "13.2",
  slokas: [
    { verse: "13.1", sanskrit: "अर्जुन उवाच |\nप्रकृतिं पुरुषं चैव क्षेत्रं क्षेत्रज्ञमेव च |\nएतद्वेदितुमिच्छामि ज्ञानं ज्ञेयं च केशव ||", transliteration: "arjuna uvācha |\nprakṛitiṁ puruṣhaṁ chaiva kṣhetraṁ kṣhetra-jñam eva cha |\netad veditum ichchhāmi jñānaṁ jñeyaṁ cha keśhava ||", meaning: "Arjuna said: O my dear Krishna, I wish to know about prakriti [nature], purusha [the enjoyer], and the field and the knower of the field, and of knowledge and the object of knowledge.", lesson: "The Curiosity of the Soul. Asking deep questions about the nature of reality is the first sign of spiritual maturity." },
    { verse: "13.2", sanskrit: "श्रीभगवानुवाच |\nइदं शरीरं कौन्तेय क्षेत्रमित्यभिधीयते |\nएतद्यो वेत्ति तं प्राहुः क्षेत्रज्ञ इति तद्विदः ||", transliteration: "śhrī-bhagavān uvācha |\nidaṁ śharīraṁ kaunteya kṣhetram ity abhidhīyate |\netad yo vetti taṁ prāhuḥ kṣhetra-jña iti tad-vidaḥ ||", meaning: "The Supreme Lord said: This body, O son of Kunti, is called the field, and one who knows this body is called the knower of the field.", lesson: "The Observer. You are not your body; you are the one inhabiting and observing it. Learn to detach your identity from physical aches or appearances." },
    { verse: "13.3", sanskrit: "क्षेत्रज्ञं चापि मां विद्धि सर्वक्षेत्रेषु भारत |\nक्षेत्रक्षेत्रज्ञयोर्ज्ञानं यत्तज्ज्ञानं मतं मम ||", transliteration: "kṣhetra-jñaṁ chāpi māṁ viddhi sarva-kṣhetreṣhu bhārata |\nkṣhetra-kṣhetrajñayor jñānaṁ yat taj jñānaṁ mataṁ mama ||", meaning: "O scion of Bharata, you should understand that I am also the knower in all bodies, and to understand this body and its knower is called knowledge. That is My opinion.", lesson: "Common Humanity. The same divine consciousness that observes your life is also observing everyone else's. We are all 'classmates' in this school of life." },
    { verse: "13.6", sanskrit: "महाभूतान्यहङ्कारो बुद्धिरव्यक्तमेव च |\nइन्द्रियाणि दशैकं च पञ्च चेन्द्रियगोचराः ||", transliteration: "mahā-bhūtāny ahankāro buddhir avyaktam eva cha |\nindriyāṇi daśhaikaṁ cha pañcha chendriya-gocharāḥ ||", meaning: "The five gross elements, false ego, intelligence, the unmanifested, the ten senses and the mind, the five sense objects...", lesson: "Mapping the Machine. Understand the 'hardware' of your existence so you can operate it better without being slave to its impulses." },
    { verse: "13.8", sanskrit: "अमानित्वमदम्भित्वमहिंसा क्षान्तिरार्जवम् |\nआचार्योपासनं शौचं स्थैर्यमात्मविनिग्रहः ||", transliteration: "amānitvam adambhitvam ahinsā kṣhāntir ārjavam |\nāchāryopāsanaṁ śhauchaṁ thairyam ātma-vinigrahaḥ ||", meaning: "Humility, pridelessness, nonviolence, tolerance, simplicity, service to the guru, purity, steadfastness, self-control...", lesson: "Real Knowledge is Behavior. Spirituality is not about what you know, but how you treat others and yourself. These 20 qualities are the true syllabus of life." },
    { verse: "13.10", sanskrit: "मयि चानन्ययोगेन भक्तिरव्यभिचारिणी |\nविविक्तदेशसेवित्वमरतिर्जनसंसदि ||", transliteration: "mayi chānanya-yogena bhaktir avyabhichāriṇī |\nvivikta-deśha-sevitvam aratir jana-saṁsadi ||", meaning: "...constant and unalloyed devotion to Me; aspiring to live in a solitary place; detachment from the general mass of people...", lesson: "Create Sacred Space. Dedicate time each day to be alone with your soul. The noise of the crowd can often drown out the music of Truth." },
    { verse: "13.12", sanskrit: "अध्यात्मज्ञाननित्यत्वं तत्त्वज्ञानार्थदर्शनम् |\nएतज्ज्ञानमिति प्रोक्तमज्ञानं यदतोऽन्यथा ||", transliteration: "adhyātma-jñāna-nityatvaṁ tattva-jñānārtha-darśhanam |\netaj jñānam iti proktam ajñānaṁ yad ato ’nyathā ||", meaning: "...accepting the importance of self-realization; and philosophical search for the Absolute Truth—all these I declare to be knowledge, and besides this whatever there may be is ignorance.", lesson: "Prioritize Truth. Information is not knowledge. True knowledge is that which leads to your internal freedom and understanding of reality." },
    { verse: "13.14", sanskrit: "सर्वतः पाणिपादं तत्सर्वतोऽक्षिशिरोमुखम् |\nसर्वतः श्रुतिमल्लोके सर्वमावृत्य तिष्ठति ||", transliteration: "sarvataḥ pāṇi-pādaṁ tat sarvato ’kṣhi-śhiro-mukham |\nsarvataḥ śhrutimal loke sarvam āvṛitya tiṣhṭhati ||", meaning: "Everywhere are His hands and legs, His eyes, heads and faces, and He has ears everywhere. In this way the Supersoul exists, pervading everything.", lesson: "Universal Presence. You are never truly alone. The Divine is watching and supporting you through every eye and hand you encounter." },
    { verse: "13.22", sanskrit: "पुरुषः प्रकृतिस्थो हि भुङ्क्ते प्रकृतिजान्गुणान् |\nकारणं गुणसङ्गोऽस्य सदसद्योनिजन्मसु ||", transliteration: "puruṣhaḥ prakṛiti-stho hi bhuṅkte prakṛitija-guṇān |\nkāraṇaṁ guṇa-saṅgo ’sya sad-asad-yoni-janmasu ||", meaning: "The living entity in material nature thus follows the ways of life, enjoying the three modes of nature. This is due to his association with that material nature. Thus he meets with good and evil among various species.", lesson: "Choose your Company. Your 'vibe' and your future are determined by what you associate with. Choose uplifting thoughts, people, and environments." },
    { verse: "13.24", sanskrit: "ध्यानेनात्मनि पश्यन्ति केचिदात्मानमात्मना |\nअन्ये साङ्ख्येन योगेन कर्मयोगेन चापरे ||", transliteration: "dhyānenātmani paśhyanti kechid ātmānam ātmanā |\nanye sāṅkhyena yogena karma-yogena chāpare ||", meaning: "Some perceive the Supersoul within themselves through meditation, others through the cultivation of knowledge, and still others through working without fruitive desires.", lesson: "Many Paths, One Goal. Whether you are a thinker, a doer, or a meditator, your path is valid. Find the one that fits your nature." },
    { verse: "13.28", sanskrit: "समं सर्वेषु भूतेषु तिष्ठन्तं परमेश्वरम् |\nविनश्यत्स्वविनश्यन्तं यः पश्यति स पश्यति ||", transliteration: "samaṁ sarveṣhu bhūteṣhu tiṣhṭhantaṁ parameśhwaram |\nvinaśhyatsv avinaśhyantaṁ yaḥ paśhyati sa paśhyati ||", meaning: "One who sees the Supersoul accompanying the individual soul in all bodies, and who understands that neither the soul nor the Supersoul within the destructible body is ever destroyed, actually sees.", lesson: "True Vision. Looking at the 'temporary' part of a person (their mood, their age) is just looking; seeing the 'eternal' part of them is truly seeing." },
    { verse: "13.34", sanskrit: "यथा प्रकाशयत्येकः कृत्स्नलोकमिमं रविः |\nक्षेत्रं क्षेत्री तथा कृत्स्नप्रकाशयति भारत ||", transliteration: "yathā prakāśhayaty ekaḥ kṛitsnaṁ lokam imaṁ raviḥ |\nkṣhetraṁ kṣhetrī tathā kṛitsnaṁ prakāśhayati bhārata ||", meaning: "O son of Bharata, as the sun alone illuminates all this universe, so does the living entity, one within the body, illuminate the entire body by consciousness.", lesson: "The Power of Consciousness. Your awareness is like a sun. Whatever you shine your attention on becomes bright. Use this light to illumine your path." }
  ]
};