import { Chapter } from './types';

export const ch14: Chapter = {
  id: 14,
  name: "Gunatraya-Vibhaga Yoga",
  meaning: "The Yoga of the Three Modes of Nature",
  slokas_count: 27,
  summary: "Krishna explains the three psychological 'modes' (Gunas)—Sattva (goodness), Rajas (passion), and Tamas (ignorance)—and how they influence human behavior and spiritual growth.",
  themes: ["Modes of Nature", "Bondage", "Transcendence", "Gunas"],
  featured_verse: "14.19",
  slokas: [
    { verse: "14.5", sanskrit: "सत्त्वं रजस्तम इति गुणाः प्रकृतिसम्भवाः |\nनिबध्नन्ति महाबाहो देहे देहिनमव्ययम् ||", transliteration: "sattvaṁ rajas tama iti guṇāḥ prakṛiti-sambhavāḥ |\nnibadhnanti mahā-bāho dehe dehinam avyayam ||", meaning: "Material nature consists of three modes—sattva [goodness], rajas [passion] and tamas [ignorance]. When the eternal living entity comes in contact with nature, O mighty-armed Arjuna, he becomes conditioned by these modes.", lesson: "Understanding Conditioning. We are all wearing 'colored glasses' (the Gunas). Recognizing the color allows us to see the world more objectively." },
    { verse: "14.6", sanskrit: "तत्र सत्त्वं निर्मलत्वात्प्रकाशकमनामयम् |\nसुखसङ्गेन बध्नाति ज्ञानसङ्गेन चानघ ||", transliteration: "tatra sattvaṁ nirmalatvāt prakāśhakam anāmayam |\nsukha-saṅgena badhnāti jñāna-saṅgena chānagha ||", meaning: "O sinless one, the mode of goodness, being purer than the others, is illuminating, and it frees one from all sinful reactions. Those situated in that mode become conditioned by a sense of happiness and knowledge.", lesson: "The Mode of Goodness (Sattva). Strive for clarity and kindness. Even though it's still a 'bond', it's a golden one that leads toward liberation." },
    { verse: "14.7", sanskrit: "रजो रागात्मकं विद्धि तृष्णासङ्गसमुद्भवम् |\nतन्निबध्नाति कौन्तेय कर्मसङ्गेन देहिनम् ||", transliteration: "rajo rāgātmakaṁ viddhi tṛiṣhṇā-saṅga-samudbhavam |\ntan nibadhnāti kaunteya karma-saṅgena dehinam ||", meaning: "The mode of passion is born of unlimited desires and longings, O son of Kunti, and because of this the embodied living entity is bound to material fruitive actions.", lesson: "The Mode of Passion (Rajas). Beware of 'unlimited' desires. Passion drives us to work hard, but it can also make us restless and stressed." },
    { verse: "14.8", sanskrit: "तमस्त्वज्ञानजं विद्धि मोहनं सर्वदेहिनाम् |\nप्रमादालस्यनिद्राभिस्तन्निबध्नाति भारत ||", transliteration: "tamas tv ajñāna-jaṁ viddhi mohanaṁ sarva-dehinām |\npramādālasya-nidrābhis tan nibadhnāti bhārata ||", meaning: "O son of Bharata, know that the mode of darkness, born of ignorance, is the delusion of all embodied living entities. The results of this mode are madness, indolence and sleep, which bind the conditioned soul.", lesson: "The Mode of Ignorance (Tamas). Laziness and procrastination are spiritual blocks. Wake up and take conscious action to break the fog." },
    { verse: "14.10", sanskrit: "रजस्तमश्चाभिभूय सत्त्वं भवति भारत |\nरजः सत्त्वं तमश्चैव तमः सत्त्वं रजस्तथा ||", transliteration: "rajas tamaśh chābhibhūya sattvaṁ bhavati bhārata |\nrajaḥ sattvaṁ tamaśh chaiva tamaḥ sattvaṁ rajas tathā ||", meaning: "Sometimes the mode of goodness becomes prominent, defeating the modes of passion and ignorance, O son of Bharata. Sometimes the mode of passion defeats goodness and ignorance, and at other times ignorance defeats goodness and passion. In this way there is always competition for supremacy.", lesson: "Managing your Moods. Your internal state is a battlefield. Be conscious of which 'mode' is winning right now and steer yourself toward Sattva." },
    { verse: "14.11", sanskrit: "सर्वद्वारेषु देहेऽस्मिन्प्रकाश उपजायते |\nज्ञानं यदा तदा विद्याद्विवृद्धं सत्त्वमित्युत ||", transliteration: "sarva-dvāreṣhu dehe ’smin prakāśha upajāyate |\njñānaṁ yadā tadā vidyād vivṛiddhaṁ sattvam ity uta ||", meaning: "The manifestations of the mode of goodness can be experienced when all the gates of the body are illumined by knowledge.", lesson: "The Sign of Progress. When you feel clear-headed, kind, and peaceful, you are in Sattva. This is the optimal state for making decisions." },
    { verse: "14.17", sanskrit: "सत्त्वात्सञ्जायते ज्ञानं रजसो लोभ एव च |\nप्रमादमोहौ तमसो भवतोऽज्ञानमेव च ||", transliteration: "sattvāt sañjāyate jñānaṁ rajaso lobha eva cha |\npramāda-mohau tamaso bhavato ’jñānam eva cha ||", meaning: "From the mode of goodness, real knowledge develops; from the mode of passion, greed develops; and from the mode of ignorance, foolishness, madness and illusion develop.", lesson: "Cause and Effect. Your current dominant mode determines your future results. Choose kindness (Sattva) to get wisdom; choose greed (Rajas) and get stress." },
    { verse: "14.18", sanskrit: "ऊर्ध्वं गच्छन्ति सत्त्वस्था मध्ये तिष्ठन्ति राजसाः |\nजघन्यगुणवृत्तिस्था अधो गच्छन्ति तामसाः ||", transliteration: "ūrdhvaṁ gachchhanti sattva-sthā madhye tiṣhṭhanti rājasāḥ |\njaghanya-guṇa-vṛitti-sthā adho gachchhanti tāmasāḥ ||", meaning: "Those situated in the mode of goodness gradually go upward to the higher planets; those in the mode of passion live on the earthly planets; and those in the abominable mode of ignorance go down to the hellish worlds.", lesson: "The Elevator of Life. Your habits are the buttons on the elevator of your soul's journey. Always press the button for 'Up'." },
    { verse: "14.19", sanskrit: "नान्यं गुणेभ्यः कर्तारं यदा द्रष्टानुपश्यति |\nगुणेभ्यश्च परं वेत्ति मद्भावं सोऽधिगच्छति ||", transliteration: "nānyaṁ guṇebhyaḥ kartāraṁ yadā draṣhṭānupaśhyati |\nguṇebhyaśh cha paraṁ vetti mad-bhāvaṁ so ’dhigachchhati ||", meaning: "When one rightly sees that in all activities no other performer is at work than these modes of nature, and when one knows the Supreme Lord, who is transcendental to all these modes, he attains My spiritual nature.", lesson: "Transcendence. Don't take your bad moods personally; they are just 'weather patterns' of the Gunas. Your true self is the sky behind the clouds." },
    { verse: "14.22", sanskrit: "श्रीभगवानुवाच |\nप्रकाशं च प्रवृत्तिं च मोहमेव च पाण्डव |\nन द्वेष्टि सम्प्रवृत्तानि न निवृत्तानि काङ्क्षति ||", transliteration: "śhrī-bhagavān uvācha |\nprakāśhaṁ cha pravṛittiṁ cha moham eva cha pāṇḍava |\nna dveṣhṭi sampravṛittāni na nivṛittāni kāṅkṣhati ||", meaning: "The Supreme Lord said: O son of Pandu, he who does not hate illumination, attachment and delusion when they are present, nor longs for them when they disappear...", lesson: "Emotional Stability. A master doesn't fight his feelings; he observes them come and go like waves on a beach, staying centered in the depths." },
    { verse: "14.26", sanskrit: "मां च योऽव्यभिचारेण भक्तियोगेन सेवते |\nस गुणान्समतीत्यैतान्ब्रह्मभूयाय कल्पते ||", transliteration: "māṁ cha yo ’vyabhichāreṇa bhakti-yogena sevate |\nsa guṇān samatītyaitān brahma-bhūyāya kalpate ||", meaning: "One who engages in full devotional service, unfailing in all circumstances, at once transcends the modes of material nature and comes to the level of Brahman.", lesson: "The shortcut. Consistent love and devotion (Bhakti) act as an 'express lane' to transcend the complexities of your own psychology." },
    { verse: "14.27", sanskrit: "ब्रह्मणो हि प्रतिष्ठाहममृतस्याव्ययस्य च |\nशाश्वतस्य च धर्मस्य सुखस्यैकान्तिकस्य च ||", transliteration: "brahmaṇo hi pratiṣhṭhāham amṛitasyāvyayasya cha |\nśhāśhvatasya cha dharmasya sukhasyaikāntikasya cha ||", meaning: "And I am the basis of the impersonal Brahman, which is immortal, imperishable and eternal and is the constitutional position of ultimate happiness.", lesson: "The Ultimate Ground. Trust that at the core of all existence—and your own soul—is a state of indestructible joy and life." }
  ]
};