
import { Chapter } from './types';

export const ch15: Chapter = {
  id: 15,
  name: "Purushottama Yoga",
  meaning: "The Yoga of the Supreme Divine Personality",
  slokas_count: 20,
  summary: "Krishna explains the nature of the material world using the metaphor of an upside-down banyan tree. He describes the soul's journey and identifies Himself as the Supreme Being (Purushottama), beyond both the perishable and imperishable.",
  themes: ["Cosmic Metaphor", "Divine Essence", "Transcendence", "Source", "Supreme Being"],
  featured_verse: "15.15",
  slokas: [
    { verse: "15.1", sanskrit: "श्रीभगवानुवाच |\nऊर्ध्वमूलमधःशाखमश्वत्थं प्राहुरव्ययम् |\nछन्दांसि यस्य पर्णानि यस्तं वेद स वेदवित् ||", transliteration: "śhrī-bhagavān uvācha |\nūrdhva-mūlam adhaḥ-śhākham aśhvatthaṁ prāhur avyayam |\nchhandāṅsi yasya parṇāni yas taṁ veda sa veda-vit ||", meaning: "The Supreme Lord said: There is a banyan tree which has its roots upward and its branches down and whose leaves are the Vedic hymns. One who knows this tree is the knower of the Vedas.", lesson: "Look to the Source. The material world is a reflection of a higher spiritual reality. To understand life, look at the 'root'—the Divine." },
    { verse: "15.2", sanskrit: "अधश्चोर्ध्वं प्रसृतास्तस्य शाखा\nगुणप्रवृद्धा विषयप्रवालाः |\nअधश्च मूलान्यनुसन्ततानि\nकर्मानुबन्धीनि मनुष्यलोके ||", transliteration: "adhaśh chordhvaṁ prasṛitās tasya śhākhā\nguṇa-pravṛiddhā viṣhaya-pravālāḥ |\nadhaśh cha mūlāny anusantatāni\nkarmānubandhīni manuṣhya-loke ||", meaning: "The branches of this tree extend downward and upward, nourished by the three modes of material nature, with the sense objects as its buds. The roots also go down, causing the flow of karma in human society.", lesson: "Understand the web of desire. Our actions and cravings keep us bound to this world. Awareness of this structure is the first step to freedom." },
    { verse: "15.3", sanskrit: "न रूपमस्येह तथोपलभ्यते\nनान्तो न चादिर्न च सम्प्रतिष्ठा |\nअश्वत्थमेनं सुविरूढमूल\nमसङ्गशस्त्रेण दृढेन छित्त्वा ||", transliteration: "na rūpam asyeha tathopalabhyate\nnānto na chādir na cha sampratiṣhṭhā |\naśhvattham enaṁ su-virūḍha-mūlam\nasaṅga-śhastreṇa dṛiḍhena chhittvā ||", meaning: "The real form of this tree cannot be perceived in this world, nor its end, nor its beginning, nor its foundation. One must cut down this strongly rooted banyan tree with the sharp weapon of detachment.", lesson: "The power of 'No'. Detachment (Asanga) is the only tool powerful enough to break the cycle of habitual behavior and desire." },
    { verse: "15.4", sanskrit: "ततः पदं तत्परिमार्गितव्यं\nयस्मिन्गता न निवर्तन्ति भूयः |\nतमेव चाद्यं पुरुषं प्रपद्ये\nयतः प्रवृत्तिः प्रसृता पुराणी ||", transliteration: "tataḥ padaṁ tat parimārgitavyaṁ\nyasmin gatā na nivartanti bhūyaḥ |\ntam eva chādyaṁ puruṣhaṁ prapadye\nyataḥ pravṛittiḥ prasṛitā purāṇī ||", meaning: "Thereafter, one must seek that goal from which there is no return, surrendering to that Primeval Person from whom this ancient process of creation emanated.", lesson: "Seek the Ultimate. Aim for a state of consciousness that is beyond the reach of temporary ups and downs." },
    { verse: "15.5", sanskrit: "निर्मानमोहा जितसङ्गदोषा\nअध्यात्मनित्या विनिवृत्तकामाः |\nद्वन्द्वैर्मुक्ताः सुखदुःखसंज्ञै\nर्गच्छन्त्यमूढाः पदमव्ययंतत् ||", transliteration: "nir-māna-mohā jita-saṅga-doṣhā\nadhyātma-nityā vinivṛitta-kāmāḥ |\ndvandvair muktāḥ sukha-duḥkha-sañjñair\ngachchha nty amūḍhāḥ padam avyayaṁ tat ||", meaning: "Those who are free from pride and delusion, who have conquered the vice of attachment, who are constantly dwelling in the Self, whose desires are completely stilled, and who are liberated from the dualities of pleasure and pain, reach that eternal state.", lesson: "The checklist for liberation: Humility, Clarity, Detachment, Self-Awareness, and Peace." },
    { verse: "15.6", sanskrit: "न तद्भासयते सूर्यो न शशाङ्को न पावकः |\nयद्गत्वा न निवर्तन्ते तद्धाम परमं मम ||", transliteration: "na tad bhāsayate sūryo na śhaśhāṅko na pāvakaḥ |\nyad gatvā na nivartante tad dhāma paramaṁ mama ||", meaning: "That supreme abode of Mine is not illumined by the sun or moon, nor by fire. Once reaching it, one never returns to this material world.", lesson: "Inner Light. The highest state of consciousness provides its own light; it doesn't depend on any external source for happiness." },
    { verse: "15.7", sanskrit: "ममैवांशो जीवलोके जीवभूतः सनातनः |\nमनःषष्ठानीन्द्रियाणि प्रकृतिस्थानि कर्षति ||", transliteration: "mamaivāṁśho jīva-loke jīva-bhūtaḥ sanātanaḥ |\nmanaḥ-ṣhaṣhṭhānīndriyāṇi prakṛiti-sthāni karṣhati ||", meaning: "The living entities in this conditioned world are My eternal fragmental parts. Due to conditioned life, they are struggling very hard with the six senses, which include the mind.", lesson: "You are Divine. Realize your inherent greatness and stop identifying solely with the struggle of the mind and senses." },
    { verse: "15.8", sanskrit: "शरीरं यदवाप्नोति यच्चाप्युत्क्रामतीश्वरः |\nगृहीत्वैतानि संयाति वायुर्गन्धानिवाशयात् ||", transliteration: "śharīraṁ yad avāpnoti yach chāpy utkrāmatīśhvaraḥ |\ngṛihītvaitāni saṁyāti vāyur gandhān ivāśhayāt ||", meaning: "As the air carries fragrances from their source, the individual soul carries the mind and senses from the body it leaves into the new body it enters.", lesson: "The journey of the soul. You carry your mental 'fragrance'—your habits and thoughts—with you. Cultivate a beautiful mind today." },
    { verse: "15.9", sanskrit: "श्रोत्रं चक्षुः स्पर्शनं च रसनं घ्राणमेव च |\nअधिष्ठाय मनश्चायं विषयानुपसेवते ||", transliteration: "śhrotraṁ chakṣhuḥ sparśhanaṁ cha rasanaṁ ghrāṇam eva cha |\nadhiṣhṭhāya manaśh chāyaṁ viṣhayān upasevate ||", meaning: "The soul, dwelling in the ear, eye, touch, taste, and smell, and also in the mind, enjoys the objects of the senses.", lesson: "Mindful observation. Be aware of how your soul 'uses' the senses to experience the world. Don't let the instruments dictate the music." },
    { verse: "15.10", sanskrit: "उत्क्रामन्तं स्थितं वापि भुञ्जानं वा गुणान्वितम् |\nविमूढा नानुपश्यन्ति पश्यन्ति ज्ञानचक्षुषः ||", transliteration: "utkrāmantaṁ sthitaṁ vāpi bhuñjānaṁ vā guṇānvitam |\nvimūḍhā nānupaśhyanti paśhyanti jñāna-chakṣhuṣhaḥ ||", meaning: "The deluded do not perceive the soul as it leaves the body, or as it stays in the body, or as it enjoys sense objects. Only those with the eye of knowledge can see this.", lesson: "Vision vs. Sight. Real knowledge allows you to see the spiritual essence beneath the surface of physical life." },
    { verse: "15.11", sanskrit: "यतन्तो योगिनश्चैनं पश्यन्त्यात्मन्यवस्थितम् |\nयतन्तोऽप्यकृतात्मानो नैनं पश्यन्त्यचेतसः ||", transliteration: "yatanto yoginaśh chainaṁ paśhyanty ātmany avasthitam |\nyatanto ’py akṛitātmāno nainaṁ paśhyanty achetasaḥ ||", meaning: "Striving yogis can see the soul clearly, but those who are not purified and lack self-realization cannot see it, even if they try.", lesson: "Preparation of the vessel. To see the Divine within, you must first clean the 'mirror' of your mind through discipline and purity." },
    { verse: "15.12", sanskrit: "यदादित्यगतं तेजो जगद्भासयतेऽखिलम् |\nयच्चन्द्रमसि यच्चाग्नौ तत्तेजो विद्धि मामकम् ||", transliteration: "yad āditya-gataṁ tejo jagad bhāsayate ’khilam |\nyach chandramasi yach chāgnau tat tejo viddhi māmakam ||", meaning: "The light of the sun that illumines the entire world, and the light in the moon and in fire, know that light to be Mine.", lesson: "Universal Energy. Every source of energy and light in the universe is a manifestation of the Divine power." },
    { verse: "15.13", sanskrit: "गामाविश्य च भूताणि धारयाम्यहमोजसा |\nपुष्णामि चौषधीः सर्वाः सोमो भूत्वा रसात्मकः ||", transliteration: "gām āviśhya cha bhūtāni dhārayāmy aham ojasā |\npuṣhṇāmi chauṣhadhīḥ sarvāḥ somo bhūtvā rasātmakaḥ ||", meaning: "Entering the earth, I support all beings by My vital energy. Becoming the moon, I nourish all plants by providing the sap of life.", lesson: "Nourishment. Recognize the Divine presence in the food you eat and the earth that sustains you." },
    { verse: "15.14", sanskrit: "अहं वैश्वानरो भूत्वा प्राणिनां देहमाश्रितः |\nप्राणापानसमायुक्तः पचाम्यन्नं चतुर्विधम् ||", transliteration: "ahaṁ vaiśhvānaro bhūtvā prāṇināṁ deham āśhritaḥ |\nprāṇāpāna-samāyuktaḥ pachāmy annaṁ chatur-vidham ||", meaning: "I am the fire of digestion in the bodies of all living beings, and joining with the air of life, I digest the four kinds of food.", lesson: "The Sacred Body. Even digestion is a divine act. Treat your body with respect as a temple of the Supreme." },
    { verse: "15.15", sanskrit: "सर्वस्य चाहं हृदि सन्निविष्टो\nमत्तः स्मृतिर्ज्ञानमपोहनं च |\nवेदैश्च सर्वैरहमेव वेद्यो\nवेदान्तकृद्वेदविदेव चाहम् ||", transliteration: "sarvasya chāhaṁ hṛidi sanniviṣhṭo |\nmattaḥ smṛitir jñānam apohanaṁ cha |\nvedaiśh cha sarvair aham eva vedyo\nvedānta-kṛid veda-vid eva chāham ||", meaning: "I am seated in the hearts of all living beings. From Me come memory, knowledge, and forgetfulness. By all the Vedas, I am to be known; indeed, I am the compiler of the Vedanta and the knower of the Vedas.", lesson: "The Internal Compass. Trust your intuition and insights; they are gifts from the Divine presence within you." },
    { verse: "15.16", sanskrit: "द्वाविमौ पुरुषौ लोके क्षरश्चाक्षर एव च |\nक्षरः सर्वाणि भूताणि कूटस्थोऽक्षर उच्यते ||", transliteration: "dvāv imau puruṣhau loke kṣharaśh chākṣhara eva cha |\nkṣharaḥ sarvāṇi bhūtāni kūṭa-stho ’kṣhara uchyate ||", meaning: "There are two kinds of beings in the world: the perishable and the imperishable. All beings in the material world are perishable, and the liberated soul is called imperishable.", lesson: "Discernment. Distinguish between what is temporary (your circumstances) and what is eternal (your spirit)." },
    { verse: "15.17", sanskrit: "उत्तमः पुरुषस्त्वन्यः परमात्मेत्युदाहृतः |\nयो लोकत्रयमाविश्य बिभर्त्यव्यय ईश्वरः ||", transliteration: "uttamaḥ puruṣhas tv anyaḥ paramātmety udāhṛitaḥ |\nyo loka-trayam āviśhya bibharty avyaya īśhvaraḥ ||", meaning: "But besides these two, there is the Supreme Divine Person, who is called the Super-soul (Paramatma). He is the indestructible Lord who enters the three worlds and sustains them.", lesson: "The Supreme Overseer. Beyond the individual soul lies the universal Spirit that holds everything together." },
    { verse: "15.18", sanskrit: "यस्मात्क्षरमतीतोऽहमक्षरादपि चोत्तमः |\nअतोऽस्मि लोके वेदे च प्रथितः पुरुषोत्तमः ||", transliteration: "yasmāt kṣharam atīto ’ham akṣharād api chottamaḥ |\nato ’smi loke vede cha prathitaḥ puruṣhottamaḥ ||", meaning: "Because I am transcendental, beyond both the perishable and the imperishable, I am celebrated in the world and in the Vedas as the Supreme Person (Purushottama).", lesson: "Identity of the Divine. Krishna identifies Himself as the peak of reality, providing a clear target for our devotion." },
    { verse: "15.19", sanskrit: "यो मामेवमसंमूढो जानाति पुरुषोत्तमम् |\nस सर्वविद्भजति मां सर्वभावेन भारत ||", transliteration: "yo mām evam asammūḍho jānāti puruṣhottamam |\nsa sarva-vid bhajati māṁ sarva-bhāvena bhārata ||", meaning: "Whoever knows Me as the Supreme Divine Personality, without doubt, is the knower of everything. He engages with all his heart in My devotional service, O son of Bharata.", lesson: "The Ultimate Knowledge. Knowing the Divine essence is like having the key to all other secrets of life." },
    { verse: "15.20", sanskrit: "इति गुह्यतमं शास्त्रमिदमुक्तं मयाऽनघ |\nएतद्बुद्ध्वा बुद्धिमान्स्यात्कृतकृत्यश्च भारत ||", transliteration: "iti guhyatamaṁ śhāstram idam uktaṁ mayānagha |\netad buddhvā buddhimān syāt kṛita-kṛityaśh cha bhārata ||", meaning: "This most secret science has been revealed by Me, O sinless one. One who understands this becomes truly wise and all his endeavors reach completion.", lesson: "Wisdom and Fulfillment. Spiritual understanding isn't just theory; it brings a sense of completeness (krita-kritya) to all your actions." }
  ]
};
