import { Chapter } from './types';

export const ch16: Chapter = {
  id: 16,
  name: "Daivasura-Sampad-Vibhaga Yoga",
  meaning: "The Yoga of the Divine and Demonic Traits",
  slokas_count: 24,
  summary: "Krishna lists the qualities that lead to spiritual liberation (Divine) and those that lead to bondage and suffering (Demonic), providing a moral compass for life.",
  themes: ["Virtue vs Vice", "Morality", "Self-Improvement", "Gateways to Hell"],
  featured_verse: "16.21",
  slokas: [
    { verse: "16.1", sanskrit: "श्रीभगवानुवाच |\nअभयं सत्त्वसंशुद्धिर्ज्ञानयोगव्यवस्थितिः |\nदानं दमश्च यज्ञश्च स्वाध्यायस्तप आर्जवम् ||", transliteration: "śhrī-bhagavān uvācha |\nabhayaṁ sattva-saṁśhuddhir jñāna-yoga-vyavasthitiḥ |\ndānaṁ damaśh cha yajñaśh cha svādhyāyas tapa ārjavam ||", meaning: "The Supreme Lord said: Fearlessness; purification of one’s existence; cultivation of spiritual knowledge; charity; self-control; performance of sacrifice; study of the Vedas; austerity; simplicity...", lesson: "Fearlessness is First. Courage is the foundation of all other virtues. Without fearlessness, you cannot be truly honest or kind." },
    { verse: "16.2", sanskrit: "अहिंसा सत्यमक्रोधस्त्यागः शान्तिरपैशुनम् |\nदया भूतेष्वलोलुप्त्वं मार्दवं ह्रीरचापलम् ||", transliteration: "ahinsā satyam akrodhas tyāgaḥ śhāntir apaiśhunam |\ndayā bhūteṣhv aloluptvaṁ mārdavaṁ hrīr achāpalam ||", meaning: "...nonviolence; truthfulness; freedom from anger; renunciation; tranquillity; aversion to faultfinding; compassion for all living entities; freedom from covetousness; gentleness; modesty; steady determination...", lesson: "The Character Check. Use this list as a mirror. If you find fault-finding or anger in your heart, work on replacing them with compassion and determination." },
    { verse: "16.4", sanskrit: "दम्भो दर्पोऽभिमानश्च क्रोधः पारुष्यमेव च |\nअज्ञानं चाभिजातस्य पार्थ सम्पदमासुरीम् ||", transliteration: "dambho darpo ’bhimānaśh cha krodhaḥ pāruṣhyam eva ch |\najñānaṁ chābhijātasya pārtha sampadam āsurīm ||", meaning: "Pride, arrogance, conceit, anger, harshness and ignorance—these qualities belong to those of demoniac nature, O son of Pritha.", lesson: "The Danger Zone. Pride and harshness are the 'red flags' of the soul. Catch them early before they become habits that ruin your peace." },
    { verse: "16.5", sanskrit: "दैवी सम्पद्विमोक्षाय निबन्धायासुरी मता |\nमा शुचः सम्पदं दैवीमभिजातोऽसि पाण्डव ||", transliteration: "daivī sampad vimokṣhāya nibandhāyāsurī matā |\nmā śhuchaḥ sampadaṁ daivīm abhijāto ’si pāṇḍava ||", meaning: "The transcendental qualities are conducive to liberation, whereas the demoniac qualities make for bondage. Do not worry, O son of Pandu, for you are born with the divine qualities.", lesson: "Self-Affirmation. Trust in your inherent goodness. You have the potential for greatness; you just need to consciously nurture it." },
    { verse: "16.7", sanskrit: "प्रवृत्तिं च निवृत्तिं च जना न विदुरासुराः |\nन शौचं नापि चाचारो न सत्यं तेषु विद्यते ||", transliteration: "pravṛittiṁ cha nivṛittiṁ cha janā na vidur āsurāḥ |\nna śhauchaṁ nāpi chāchāro na satyaṁ teṣhu vidyate ||", meaning: "Those who are demoniac do not know what is to be done and what is not to be done. Neither cleanliness nor proper behavior nor truth is found in them.", lesson: "Know your 'Do's and Don'ts'. Morality is not just rules; it's the 'user manual' for a happy life. Without it, life becomes chaotic and messy." },
    { verse: "16.10", sanskrit: "काममाश्रित्य दुष्पूरं दम्भमानमदान्विताः |\nमोहाद्गृहीत्वासद्ग्राहान्प्रवर्तन्तेऽशुचिव्रताः ||", transliteration: "kāmam āśhritya duṣhpūraṁ dambha-māna-madānvitāḥ |\nmohād gṛihītvāsad-grāhān pravartante ’śhuchi-vratāḥ ||", meaning: "Taking shelter of insatiable lust and absorbed in the conceit of pride and false prestige, the demoniac, thus illusioned, are always sworn to unclean work, attracted by the impermanent.", lesson: "The Bottomless Pit. Lust and greed are never satisfied. Trying to fill them is like pouring water into a sieve. Seek satisfaction in the soul, not in objects." },
    { verse: "16.12", sanskrit: "आशापाशशतैर्बद्धाः कामक्रोधपरायणाः |\nईहन्ते कामभोगार्थमन्यायेनार्थसञ्चयान् ||", transliteration: "āśhā-pāśha-śhatair baddhāḥ kāma-krodha-parāyaṇāḥ |\nīhante kāma-bhogārtham anyāyenārtha-sañchayān ||", meaning: "Bound by a network of hundreds of thousands of desires and absorbed in lust and anger, they secure money by illegal means for sense gratification.", lesson: "The Trap of Greed. Shortcuts and illegal gains might seem fast, but they tie your soul in 'knots' of anxiety and future suffering." },
    { verse: "16.13", sanskrit: "इदमद्य मया लब्धमिमं प्राप्स्ये मनोरथम् |\nइदमस्तीदमपि मे भविष्यति पुनर्धनम् ||", transliteration: "idam adya mayā labdham imaṁ prāpsye manoratham |\nidam astīdam api me bhaviṣhyati punar dhanam ||", meaning: "The demoniac person thinks: 'So much wealth do I have today, and I will gain more according to my schemes. So much is mine now, and it will increase in the future, more and more.'", lesson: "The Illusion of Control. Ego-driven planning ignores the reality of change and the Divine will. Plan with humility, not with arrogance." },
    { verse: "16.19", sanskrit: "तानहं द्विषतः क्रूरान्संसारेषु नराधमान् |\nक्षिपाम्यजस्रमशुभानासुरीष्वेव योनिषु ||", transliteration: "tān ahaṁ dviṣhataḥ krūrān saṁsāreṣhu narādhamān |\nkṣhipāmy ajasram aśhubhān āsurīṣhv eva yoniṣhu ||", meaning: "Those who are envious and mischievous, who are the lowest among men, I perpetually cast into the ocean of material existence, into various demoniac species of life.", lesson: "The Gravity of Character. Your character acts like spiritual gravity. If you are cruel and envious, you naturally sink into lower, more difficult states of life." },
    { verse: "16.21", sanskrit: "त्रिविधं नरकस्येदं द्वारं नाशनमात्मनः |\nकामः क्रोधस्तथा लोभस्तस्मादेतत्त्रयं त्यजेत् ||", transliteration: "tri-vidhaṁ narakasyedaṁ dvāraṁ nāśhanam ātmanaḥ |\nkāmaḥ krodhas tathā lobhas tasmād etat trayaṁ tyajet ||", meaning: "There are three gates leading to this hell—lust, anger and greed. Every sane man should give these up, for they lead to the degradation of the soul.", lesson: "The Three Gates. Anger, greed, and obsession are the 'black holes' of psychology. Learn to spot them and walk away before you are pulled in." },
    { verse: "16.23", sanskrit: "यः शास्त्रविधिमुत्सृज्य वर्तते कामकारतः |\nन स सिद्धिमवाप्नोति न सुखं न परां गतिम् ||", transliteration: "yaḥ śhāstra-vidhim utsṛijya vartate kāma-kārataḥ |\nna sa siddhim avāpnoti na sukhaṁ na parāṁ gatim ||", meaning: "He who discards scriptural injunctions and acts according to his own whims attains neither perfection, nor happiness, nor the supreme destination.", lesson: "Respect the Wisdom of the Ages. Don't try to reinvent morality. The 'rules' were designed by sages to protect your happiness. Follow the map." },
    { verse: "16.24", sanskrit: "तस्माच्छास्त्रं प्रमाणं ते कार्याकार्यव्यवस्थितौ |\nज्ञात्वा शास्त्रविधानोक्तं कर्म कर्तुमिहार्हसि ||", transliteration: "tasmāch śhāstraṁ pramāṇaṁ te kāryākārya-vyavasthitau |\njñātvā śhāstra-vidhānoktaṁ karma kartum ihārhasi ||", meaning: "One should therefore understand what is duty and what is not duty by the regulations of the scriptures. Knowing such rules and regulations, you should act so that you may gradually be elevated.", lesson: "Consult the Standard. When you're not sure what to do, look at the timeless principles of the Gita. They provide a clear North Star for your actions." }
  ]
};