import { Chapter } from './types';

export const ch17: Chapter = {
  id: 17,
  name: "Shraddhatraya-Vibhaga Yoga",
  meaning: "The Yoga of the Three Kinds of Faith",
  slokas_count: 28,
  summary: "Krishna explains how our faith, food, worship, and speech are influenced by the three modes of nature, helping us refine our lifestyle and habits.",
  themes: ["Faith", "Food and Health", "Austerity", "Intentionality"],
  featured_verse: "17.3",
  slokas: [
    { verse: "17.1", sanskrit: "अर्जुन उवाच |\nये शास्त्रविधिमुत्सृज्य यजन्ते श्रद्धयान्विताः |\nतेषां निष्ठा तु का कृष्ण सत्त्वमाहो रजस्तमः ||", transliteration: "arjuna uvācha |\nye śhāstra-vidhim utsṛijya yajante śhraddhayānvitāḥ |\nteṣhāṁ niṣhṭhā tu kā kṛiṣhṇa sattvam āho rajas tamaḥ ||", meaning: "Arjuna inquired: O Krishna, what is the situation of those who do not follow the principles of scripture but worship according to their own imagination? Is it in goodness, in passion or in ignorance?", lesson: "The Heart of Faith. Arjuna asks if sincere faith matters even if one doesn't know the formal rules. The answer reveals that the 'vibe' of your heart is what truly counts." },
    { verse: "17.2", sanskrit: "श्रीभगवानुवाच |\nत्रिविधा भवति श्रद्धा देहिनां सा स्वभावजा |\nसात्त्विकी राजसी चैव तामसी चेति तां शृणु ||", transliteration: "śhrī-bhagavān uvācha |\ntri-vidhā bhavati śhraddhā dehināṁ sā swabhāva-jā |\nsāttvikī rājasī chaiva tāmasī chēti tāṁ śhṛiṇu ||", meaning: "The Supreme Lord said: According to the modes of nature acquired by the embodied soul, one’s faith can be of three kinds—in goodness, in passion or in ignorance. Now hear about this.", lesson: "Different Types of Faith. Not all 'spirituality' is the same. Some is driven by fear (Tamas), some by greed (Rajas), and some by truth (Sattva). Know which one you are choosing." },
    { verse: "17.3", sanskrit: "सत्त्वानुरूपा सर्वस्य श्रद्धा भवति भारत |\nश्रद्धामयोऽयं पुरुषो यो यच्छ्रद्धः स एव सः ||", transliteration: "sattvānurūpā sarvasya śhraddhā bhavati bhārata |\nśhraddhā-mayo ’yaṁ puruṣho yo yach-chhraddhaḥ sa eva saḥ ||", meaning: "According to one’s existence under the various modes of nature, one evolves a particular kind of faith. The living being is said to be of a particular faith according to the modes he has acquired.", lesson: "You are your Faith. Your core beliefs shape your character and your destiny. Consciously choose to believe in growth, kindness, and Truth." },
    { verse: "17.8", sanskrit: "आयुःसत्त्वबलारोग्यसुखप्रीतिविवर्धनाः |\nरस्याः स्निग्धाः स्थिरा हृद्या आहाराः सात्त्विकप्रियाः ||", transliteration: "āyuḥ-sattva-balārogya-sukha-prīti-vivardhanāḥ |\nrasyāḥ snigdhāḥ sthirā hṛidyā āhārāḥ sāttvika-priyāḥ ||", meaning: "Foods dear to those in the mode of goodness increase the duration of life, purify one’s existence and give strength, health, happiness and satisfaction. Such foods are juicy, fatty, wholesome, and pleasing to the heart.", lesson: "Conscious Eating. Food is not just fuel; it's medicine for the mind. Eat fresh, wholesome foods to keep your spirit clear and energetic." },
    { verse: "17.9", sanskrit: "कट्वम्ललवणात्युष्णतीक्ष्णरूक्षविदाहिनः |\nआहारा राजसस्येष्टा दुःखशोकामयप्रदाः ||", transliteration: "āhārā rājasasyeṣhṭā duḥkha-śhokāmaya-pradāḥ ||", meaning: "Foods that are too bitter, too sour, salty, hot, pungent, dry and burning are dear to those in the mode of passion. Such foods cause distress, misery and disease.", lesson: "Beware of Extremes. Over-stimulating foods might taste exciting, but they often leave the body and mind feeling exhausted or irritated." },
    { verse: "17.10", sanskrit: "यातयामं गतरसं पूति पर्युषितं च यत् |\nउच्छिष्टमपि चामेध्यं भोजनं तामसप्रियम् ||", transliteration: "yāta-yāmaṁ gata-rasaṁ pūti paryuṣhitaṁ cha yat |\nuchchhiṣhṭam api chāmedhyaṁ bhojanaṁ tāmasa-priyam ||", meaning: "Food prepared more than three hours before being eaten, food that is tasteless, decomposed and putrid, and food consisting of remnants and untouchable things is dear to those in the mode of ignorance.", lesson: "Freshness is Spiritual. Stale or highly processed 'junk' food keeps the mind in a fog. Respect your body by giving it fresh, life-giving energy." },
    { verse: "17.14", sanskrit: "देवद्विजगुरुप्राज्ञपूजनं शौचमार्जवम् |\nब्रह्मचर्यमहिंसा च शारीरं तप उच्यते ||", transliteration: "deva-dvija-guru-prājñā-pūjanaṁ śhaucham ārjavam |\nbrahmacharyam ahinsā cha śhārīraṁ tapa uchyate ||", meaning: "Austerity of the body consists in worship of the Supreme Lord, the Brahmins, the spiritual master, and superiors like the father and mother, and in cleanliness, simplicity, celibacy and nonviolence.", lesson: "The Discipline of the Body. Physical training is not just for the gym. Cleanliness and respect for elders are essential spiritual 'exercises'." },
    { verse: "17.15", sanskrit: "अनुद्वेगकरं वाक्यं सत्यं प्रियहितं च यत् |\nस्वाध्यायाभ्यसनं चैव वाङ्मयं तप उच्यते ||", transliteration: "anudvega-karaṁ vākyaṁ satyaṁ priya-hitaṁ cha yat |\nswādhyāyābhyasanaṁ chaiva vāṅ-mayaṁ tapa uchyate ||", meaning: "Austerity of speech consists in speaking words that are truthful, pleasing, beneficial, and not agitating to others, and also in regularly reciting Vedic literature.", lesson: "The Discipline of Words. Your voice is a tool. Use it to speak the truth, but do it kindly. If it's true but harmful, silence might be the better 'austerity'." },
    { verse: "17.16", sanskrit: "मनःप्रसादः सौम्यत्वं मौनमात्मविनिग्रहः |\nभावसंशुद्धिरित्येतत्तपो मानसमुच्यते ||", transliteration: "manaḥ-prasādaḥ saumyatvaṁ maunam ātma-vinigrahaḥ |\nbhāva-saṁśhuddhir ity etat tapo mānasam uchyate ||", meaning: "And satisfaction, simplicity, gravity, self-control and purification of one’s existence are the austerities of the mind.", lesson: "The Discipline of the Mind. Happiness is an austerity—it takes effort to stay positive. Simplicity of thought is the highest mental training." },
    { verse: "17.20", sanskrit: "दातव्यमिति यद्दानं दीयतेऽनुपकारिणे |\nदेशे काले च पात्रे च तद्दानं सात्त्विकं स्मृतम् ||", transliteration: "dātavyam iti yad dānaṁ dīyate ’nupakāriṇe |\ndeśhe kāle cha pātre cha tad dānaṁ sāttvikaṁ smṛitam ||", meaning: "Charity given out of duty, without expectation of return, at the proper time and place, and to a worthy person is considered to be in the mode of goodness.", lesson: "Pure Giving. Don't give just to get a tax break or a 'thank you'. Give because it's the right thing to do. The best charity is quiet and meaningful." },
    { verse: "17.23", sanskrit: "ॐ तत्सदिति निर्देशो ब्रह्मणस्त्रिविधः स्मृतः |\nब्राह्मणास्तेन वेदाश्च यज्ञाश्च विहिताः पुरा ||", transliteration: "om tat sad iti nirdeśho brahmaṇas tri-vidhaḥ smṛitaḥ |\nbrāhmaṇās tena vedāśh cha yajñāśh cha vihitāḥ purā ||", meaning: "From the beginning of creation, the three words om tat sat were used to indicate the Supreme Absolute Truth.", lesson: "The Sacred Sound. 'Om Tat Sat' reminds us that everything we do should be aligned with the Absolute Truth. It is a way to sanctify any action." },
    { verse: "17.28", sanskrit: "अश्रद्धया हुतं दत्तं तपस्तप्तं कृतं च यत् |\nअसदित्युच्यते पार्थ न च तत्प्रेत्य नो इह ||", transliteration: "aśhraddhayā hutaṁ dattaṁ tapas taptaṁ kṛitaṁ cha yat |\nasad ity uchyate pārtha na cha tat pretya no iha ||", meaning: "Anything done as sacrifice, charity or penance without faith, O son of Pritha, is impermanent. It is called asat and is useless both in this life and the next.", lesson: "Faith is the Engine. Actions without heart or conviction are hollow. Put your soul into whatever you do; that's what makes it 'real'." }
  ]
};