
import { Chapter } from './types';

export const ch18: Chapter = {
  id: 18,
  name: "Moksha-Upadesha Yoga",
  meaning: "The Yoga of Final Liberation",
  slokas_count: 78,
  summary: "Krishna provides a final summary of all His teachings, concluding with the ultimate instruction of complete surrender to the Divine.",
  themes: ["Renunciation", "Duty", "Ultimate Summary", "Surrender", "Final Conclusion"],
  featured_verse: "18.66",
  slokas: [
    { verse: "18.1", sanskrit: "अर्जुन उवाच |\nसंन्यासस्य महाबाहो तत्त्वमिच्छामि वेदितुम् |\nत्यागस्य च हृषीकेश पृथक्केशिनिषूदन ||", transliteration: "arjuna uvācha |\nsanyāsasya mahā-bāho tattvam ichchhāmi veditum |\ntyāgasya cha hṛiṣhīkeśha pṛithak keśhi-niṣhūdana ||", meaning: "Arjuna said: O mighty-armed one, I wish to understand the true nature of 'Sanyasa' (renunciation) and 'Tyaga' (sacrifice), O Hrishikesha, slayer of the Keshi demon.", lesson: "Clarity starts with definition. Before acting, seek to understand the subtle differences between similar concepts to choose the most righteous path." },
    { verse: "18.2", sanskrit: "श्रीभगवानुवाच |\nकाम्यानां कर्मणां न्यासं संन्यासं कवयो विदुः |\nसर्वकर्मफलत्यागं प्राहुस्त्यागं विचक्षणाः ||", transliteration: "śhrī-bhagavān uvācha |\nkāmyānāṁ karmaṇāṁ nyāsaṁ sanyāsaṁ kavayo viduḥ |\nsarva-karma-phala-tyāgaṁ prāhus tyāgaṁ vichakṣhaṇāḥ ||", meaning: "The Supreme Lord said: Giving up of actions that are motivated by desire is called Sanyasa. Giving up the fruits of all actions is called Tyaga by the wise.", lesson: "Internal Renunciation. True sacrifice is not quitting your job, but quitting the selfish desire for personal gain from your job." },
    { verse: "18.5", sanskrit: "यज्ञदानतपःकर्म न त्याज्यं कार्यमेव तत् |\nयज्ञो दानं तपश्चैव पावनानि मनीषिणाम् ||", transliteration: "yajña-dāna-tapaḥ-karma na tyājyaṁ kāryam eva tat |\nyajño dānaṁ tapaśh chaiva pāvanāni manīṣhiṇām ||", meaning: "Acts of sacrifice, charity and penance are not to be given up; they must be performed. Indeed, sacrifice, charity and penance purify even the great souls.", lesson: "Don't stop giving. Even if you feel you have achieved spiritual success, keep performing acts of service and discipline; they keep your heart clean." },
    { verse: "18.20", sanskrit: "सर्वभूतेषु येनैकं भावमव्ययमीक्षते |\nअविभक्तं विभक्तेषु तज्ज्ञानं विद्धि सात्त्विकम् ||", transliteration: "sarva-bhūteṣhu yenaikaṁ bhāvam avyayam īkṣhate |\navibhaktaṁ vibhakteṣhu taj jñānaṁ viddhi sāttvikam ||", meaning: "That knowledge by which one undivided spiritual nature is seen in all living entities, though they are divided into innumerable forms, you should understand to be in the mode of goodness.", lesson: "Unity in diversity. Seeing the same divine presence in every person, animal, and plant is the highest form of intelligence." },
    { verse: "18.42", sanskrit: "शमो दमस्तपः शौचं क्षान्तिरार्जवमेव च |\nज्ञानं विज्ञानमास्तिक्यं ब्रह्मकर्म स्वभावजम् ||", transliteration: "śhamo damas tapaḥ śhauchaṁ kṣhāntir ārjavam eva cha |\njñānaṁ vijñānam āstikyaṁ brahma-karma swabhāva-jam ||", meaning: "Peacefulness, self-control, austerity, purity, tolerance, honesty, knowledge, wisdom and religiousness—these are the natural qualities by which the Brahmins work.", lesson: "The attributes of a guide. If you wish to lead or teach, these nine qualities are your required syllabus." },
    { verse: "18.46", sanskrit: "यतः प्रवृत्तिर्भूतानां येन सर्वमिदं ततम् |\nस्वकर्मणा तमभ्यर्च्य सिद्धिं विन्दति मानवः ||", transliteration: "yataḥ pravṛittir bhūtānāṁ yena sarvam idaṁ tatam |\nsva-karmaṇā tam abhyarchya siddhiṁ vindati mānavas ||", meaning: "By performing one's natural duty for the pleasure of the Divine, from whom all beings arise and by whom the whole universe is pervaded, one attains perfection.", lesson: "Work is worship. When you do your job with excellence and offer it to the universe, you are on the highest spiritual path." },
    { verse: "18.47", sanskrit: "श्रेयान्स्वधर्मो विगुणः परधर्मात्स्वनुष्ठितात् |\nस्वभावनियतं कर्म कुर्वन्नाप्नोति किल्बिषम् ||", transliteration: "śhreyān swa-dharmo viguṇaḥ para-dharmāt sw-anuṣhṭhitāt |\nswabhāva-niyataṁ karma kurvan nāpnoti kilbiṣham ||", meaning: "It is better to engage in one's own occupation, even though one may perform it imperfectly, than to accept another's occupation and perform it perfectly. Duties prescribed according to one's own nature are never affected by sinful reactions.", lesson: "Stay in your lane. Trying to be someone else is a sin against your own soul. Be the best 'you', flaws and all." },
    { verse: "18.48", sanskrit: "सहजं कर्म कौन्तेय सदोषमपि न त्यजेत् |\nसर्वारम्भा हि दोषेण धूमेनाग्निरिवावृताः ||", transliteration: "saha-jaṁ karma kaunteya sa-doṣham api na tyajet |\nsarvārambhā hi doṣheṇa dhūmenāgnir ivāvṛitāḥ ||", meaning: "One should not give up the work born of his nature, O son of Kunti, even if such work is full of fault; for all undertakings are covered by some sort of fault, as fire is covered by smoke.", lesson: "Embrace imperfection. No work is perfect; the key is to perform it with a pure heart and dedicated spirit." },
    { verse: "18.54", sanskrit: "ब्रह्मभूतः प्रसन्नात्मा न शोचति न काङ्क्षति |\nसमः सर्वेषु भूतेषु मद्भक्तिं लभते पराम् ||", transliteration: "brahma-bhūtaḥ prasannātmā na śhochati na kāṅkṣhati |\nsamaḥ sarveṣhu bhūteṣhu mad-bhaktiṁ labhate parām ||", meaning: "One who is thus transcendentally situated at once realizes the Supreme Brahman and becomes fully joyful. He never laments or desires to have anything. He is equally disposed toward every living entity. In that state he achieves pure devotional service unto Me.", lesson: "Joy is the sign of success. When you stop complaining and start loving everyone equally, you have reached the peak of spiritual life." },
    { verse: "18.55", sanskrit: "भक्त्या मामभिजानाति यावान्यश्चास्मि तत्त्वतः |\nततो मां तत्त्वतो ज्ञात्वा विशते तदनन्तरम् ||", transliteration: "bhaktyā mām abhijānāti yāvān yaśh chāsmi tattvataḥ |\ntato māṁ tattvato jñātvā viśhate tad-anantaram ||", meaning: "Only by devotional service can one understand Me as I am, in My Divine Personality. And when one is in full consciousness of Me by such devotion, he can enter into the kingdom of God.", lesson: "The Gateway of Love. Knowledge provides the map, but love (Bhakti) is the actual entry into the Divine presence." },
    { verse: "18.57", sanskrit: "चेतसा सर्वकर्माणि मयि संन्यस्य मत्परः |\nबुद्धियोगमुपाश्रित्य मच्चित्तः सततं भव ||", transliteration: "chetasā sarva-karmāṇi mayi sannyasya mat-perah |\nbuddhi-yogam upāśhritaḥ mach-chittaḥ satataṁ bhava ||", meaning: "In all activities just depend upon Me and work always under My protection. In such devotional service, be fully conscious of Me.", lesson: "Constant Awareness. Make 'God' the background music of your life, playing silently behind every conversation and task." },
    { verse: "18.58", sanskrit: "मच्चित्तः सर्वदुर्गाणि मत्प्रसादात्तरिष्यसि |\nअथ चेत्त्वमहङ्कारान्न श्रोष्यसि विनङ्क्ष्यसि ||", transliteration: "mach-chittaḥ sarva-durgāṇi mat-prasādāt tariṣhyasi |\natha chet tvam ahankārān na śhroṣhyasi vinaṅkṣhyasi ||", meaning: "If you become conscious of Me, you will pass over all the obstacles of conditioned life by My grace. If, however, you do not work in such consciousness but act through false ego, not hearing Me, you will be lost.", lesson: "Grace vs Ego. Surrendering your ego allows Divine grace to clear your path. Holding onto ego makes the journey unnecessarily difficult." },
    { verse: "18.61", sanskrit: "ईश्वरः सर्वभूतानां हृद्देशेऽर्जुन तिष्ठति |\nभ्रामयन्सर्वभूताणि यन्त्रारूढानि मायया ||", transliteration: "īśhvaraḥ sarva-bhūtāṇāṁ hṛid-deśhe ’rjuna tiṣhṭhati |\nbhrāmayan sarva-bhūtāṇi yantrārūḍhāni māyayā ||", meaning: "The Supreme Lord dwells in the hearts of all living beings, O Arjuna. By His cosmic energy, He causes them to revolve like puppets on a machine.", lesson: "Recognize the higher hand. We are part of a grand design; understanding this leads to a life of flow rather than friction." },
    { verse: "18.62", sanskrit: "तमेव शरणं गच्छ सर्वभावेन भारत |\nतत्प्रसादात्परां शान्तिं स्थानं प्राप्स्यसि शाश्वतम् ||", transliteration: "tam eva śharaṇaṁ gachchha sarva-bhāvena bhārata |\ntat-prasādāt parāṁ śhāntim sthānaṁ prāpsyasi śhāśhvatam ||", meaning: "Surrender unto Him utterly, O Bharata. By His grace you will attain transcendental peace and the supreme and eternal abode.", lesson: "Total Surrender. When you stop fighting the universe and start trusting its source, deep and lasting peace arrives." },
    { verse: "18.63", sanskrit: "इति ते ज्ञानमाख्यातं गुह्याद्गुह्यतरं मया |\nविमृश्यैतदशेषेण यथेच्छसि तथा कुरु ||", transliteration: "iti te jñānam ākhyātaṁ guhyād guhyataraṁ mayā |\nvimṛiśhyaitad aśheṣheṇa yathechchhashi tathā kuru ||", meaning: "Thus I have explained to you knowledge still more confidential. Deliberate on this fully, and then do what you wish to do.", lesson: "God respects your free will. Spirituality is not about following rules blindly, but about deep reflection and making conscious choices." },
    { verse: "18.64", sanskrit: "सर्वगुह्यतमं भूयः शृणु मे परमं वचः |\nइष्टोऽसि मे दृढमिति ततो वक्ष्यामि ते हितम् ||", transliteration: "sarva-guhyatamaṁ bhūyaḥ śhṛiṇu me paramaṁ vachaḥ |\niṣhṭo ’si me dṛiḍham iti tato vakṣhyāmi te hitam ||", meaning: "Because you are My very dear friend, I am speaking to you My supreme instruction, the most confidential of all knowledge. Hear this from Me, for it is for your benefit.", lesson: "Divine Love. The highest truths are shared in a state of love. Listen to your heart's quiet guidance; it's the Divine speaking to a friend." },
    { verse: "18.65", sanskrit: "मन्मना भव मद्भक्तो मद्याजी मां नमस्कुरु |\nमामेवैष्यसि सत्यं ते प्रतिजाने प्रियोऽसि मे ||", transliteration: "man-manā bhava mad-bhakto mad-yājī māṁ namaskuru |\nmām evaiṣhyasi satyaṁ te pratijāne priyo ’si me ||", meaning: "Always think of Me, become My devotee, worship Me and offer your homage unto Me. Thus you will come to Me without fail. I promise you this because you are My very dear friend.", lesson: "The Promise. Sincere focus and love are the only guarantees in spiritual life. You cannot fail if you truly love the Truth." },
    { verse: "18.66", sanskrit: "सर्वधर्मान्परित्यज्य मामेकं शरणं व्रज |\nअहं त्वां सर्वपापेभ्यो मोक्षयिष्‍यामि मा शुचः ||", transliteration: "sarva-dharmān parityajya mām ekaṁ śharaṇaṁ vraja |\nahaṁ tvāṁ sarva-pāpebhyo mokṣhayiṣhyāmi mā śhuchaḥ ||", meaning: "Abandon all varieties of Dharma and just surrender unto Me. I shall deliver you from all sinful reactions. Do not fear.", lesson: "The Ultimate Instruction. Let go of your complicated ideas of 'right' and 'wrong' and simply trust the Divine. Surrender is the death of fear." },
    { verse: "18.67", sanskrit: "इदं ते नातपस्काय नाभक्ताय कदाचन |\nन चाशुश्रूषवे वाच्यं न च मां योऽभ्यसूयति ||", transliteration: "idaṁ te nātapaskāya nābhaktāya kadāchana |\nna chāśhuśhrūṣhave vāchyaṁ na cha māṁ yo ’bhyasūyati ||", meaning: "This confidential knowledge may never be explained to those who are not austere, or devoted, or engaged in devotional service, nor to one who is envious of Me.", lesson: "Qualify yourself. Wisdom only takes root in a heart prepared by discipline and open to love." },
    { verse: "18.68", sanskrit: "य इमं परमं गुह्यं मद्भक्तेष्वभिधास्यति |\nभक्तिं मयि परां कृत्वा मामेवैष्यत्यसंशयः ||", transliteration: "ya imaṁ paramaṁ guhyam mad-bhakteṣhv abhidhāsyati |\nbhaktiṁ mayi parāṁ kṛitvā mām evaiṣhyaty asanśhayaḥ ||", meaning: "For one who explains this supreme secret to the devotees, pure devotional service is guaranteed, and at the end he will come back to Me.", lesson: "Share the Light. When you help others find their way, your own path becomes infinitely brighter." },
    { verse: "18.70", sanskrit: "अध्येष्यते च य इमं धर्म्यं संवादमावयोः |\nज्ञानयज्ञेन तेनाहमिष्टः स्यामिति मे मतिः ||", transliteration: "adhyeṣhyate cha ya imaṁ dharmyaṁ saṁvādam āvayoḥ |\njñāna-yajñena tenāham iṣhṭaḥ syām iti me matiḥ ||", meaning: "And I declare that he who studies this sacred conversation of ours worships Me by his intelligence.", lesson: "Intellectual Worship. Deep study and contemplation of these truths is one of the highest forms of prayer." },
    { verse: "18.71", sanskrit: "श्रद्धावाननसूयश्च शृणुयादपि यो नरः |\nसोऽपि मुक्तः शुभाँल्लोकान्प्राप्नुयात्पुण्यकर्मणाम् ||", transliteration: "śhraddhāvān anasūyaśh cha śhṛiṇuyād api yo naraḥ |\nso ’pi muktaḥ śhubhān lokān prāpnuyāt puṇya-karmaṇām ||", meaning: "And even one who listens with faith and without envy becomes free from sinful reactions and attains to the auspicious worlds of the righteous.", lesson: "Open Ears, Open Heart. Even simply listening to these words with a good heart begins the process of inner purification." },
    { verse: "18.73", sanskrit: "अर्जुन उवाच |\nनष्टो मोहः स्मृतिर्लब्धा त्वत्प्रसादान्मयाच्युत |\nस्थितोऽस्मि गतसन्देहः करिष्ये वचनं तव ||", transliteration: "arjuna uvācha |\nnaṣhṭo mohaḥ smṛitir labdhā tvat-prasādān mayāchyuta |\nsthito ’smi gata-sandehaḥ kariṣhyē vachanaṁ tava ||", meaning: "Arjuna said: My dear Krishna, O infallible one, my illusion is now gone. I have regained my memory by Your mercy. I am now firm and free from doubt and am prepared to act according to Your instructions.", lesson: "The Fruit of Wisdom. The end of confusion is the beginning of action. When you know who you are, you know what you must do." },
    { verse: "18.74", sanskrit: "सञ्जय उवाच |\nइत्यहं वासुदेवस्य पार्थस्य च महात्मनः |\nसंवादमिममश्रौषमद्भुतं रोमहर्षणम् ||", transliteration: "sañjaya uvācha |\nity ahaṁ vāsudevasya pārthasya cha mahātmanaḥ |\nsaṁvādam imam aśhrauṣham adbhutaṁ roma-harṣhaṇam ||", meaning: "Sanjaya said: Thus have I heard the conversation of two great souls, Krishna and Arjuna. And so wonderful is that message that my hair is standing on end.", lesson: "The Experience of Truth. Real wisdom is not dry; it is thrilling, awe-inspiring, and physically transformative." },
    { verse: "18.78", sanskrit: "यत्र योगेश्वरः कृष्णो यत्र पार्थो धनुर्धरः |\nतत्र श्रीर्विजयो भूतिर्ध्रुवा नीतिर्मतिर्मम ||", transliteration: "yatra yogeśhvaraḥ kṛiṣhṇो yatra pārtho dhanur-dharaḥ |\ntatra śhrīr vijayo bhūtir dhruvā nītir matir mama ||", meaning: "Wherever there is Krishna, the Lord of Yoga, and wherever there is Arjuna, the supreme archer, there will also certainly be prosperity, victory, extraordinary power, and morality.", lesson: "The formula for success: Divine Grace (Krishna) + Human Effort (Arjuna). When wisdom and action unite, victory is certain." }
  ]
};
