
import { Chapter } from './types';

export const ch2: Chapter = {
  id: 2,
  name: "Sankhya Yoga",
  meaning: "The Yoga of Knowledge",
  slokas_count: 72,
  summary: "Krishna delivers the foundational philosophy of the Gita: the immortality of the soul, the transient nature of the body, and the secret of working without attachment.",
  themes: ["Immortality of Soul", "Dharma", "Equanimity", "Stilled Intellect"],
  featured_verse: "2.47",
  slokas: [
    { verse: "2.1", sanskrit: "सञ्जय उवाच |\nतं तथा कृपयाविष्टमश्रुपूर्णाकुलेक्षणम् |\nविषीदन्तमिदं वाक्यमुवाच मधुसूदनः ||", transliteration: "sañjaya uvācha |\ntaṁ tathā kṛipayāviṣhṭam aśhru-pūrṇākulekṣhaṇam |\nviṣhīdantam idaṁ vākyam uvācha madhusūdanaḥ ||", meaning: "Sanjaya said: Seeing Arjuna full of compassion, his mind depressed, his eyes full of tears, Madhusudana, Krishna, spoke the following words.", lesson: "Compassion is a virtue, but when it leads to the neglect of duty, it must be corrected by higher wisdom." },
    { verse: "2.2", sanskrit: "श्रीभगवानुवाच |\nकुतस्त्वा कश्मलमिदं विषमे समुपस्थितम् |\nअनार्यजुष्टमस्वर्ग्यमकीर्तिकरमर्जुन ||", transliteration: "śhrī-bhagavān uvācha |\nkutas tvā kaśhmalam idaṁ viṣhame samupasthitam |\nanārya-juṣhṭam aswargyam akīrti-karam arjuna ||", meaning: "The Supreme Lord said: My dear Arjuna, how have these impurities come upon you? They are not at all befitting a man who knows the value of life. They lead not to higher planets but to infamy.", lesson: "Confront your internal impurities. Weakness in a crisis is not nobility; it is a deviation from your true nature." },
    { verse: "2.3", sanskrit: "क्लैब्यं मा स्म गमः पार्थ नैतत्त्वय्युपपद्यते |\nक्षुद्रं हृदयदौर्बल्यं त्यक्त्वोत्तिष्ठ परन्तप ||", transliteration: "klaibyaṁ mā sma gamaḥ pārtha naitat tvayy upapadyate |\nkṣhudraṁ hṛidaya-daurbalyaṁ tyaktvottiṣhṭha perantapa ||", meaning: "O Parth, yield not to unmanliness. It does not befit you. Abandon this base weakness of heart and arise, O conqueror of enemies!", lesson: "Vulnerability is human, but staying in a state of weakness is a choice. Spiritual strength begins with the decision to stand up." },
    { verse: "2.7", sanskrit: "कार्पण्यदोषोपहतस्वभावः\nपृच्छामि त्वां धर्मसम्मूढचेताः |\nयच्छ्रेयः स्यान्निश्चितं ब्रूहि तन्मे\nशिष्यस्तेऽहं शाधि मां त्वां प्रपन्नम् ||", transliteration: "kārpaṇya-doṣhopahata-swabhāvaḥ\npṛichchhāmi tvāṁ dharma-sammūḍha-chetāḥ |\nyach-chhreyaḥ syān niśhchitaṁ brūhi tan-me\nśhiṣhyas te ’haṁ śhādhi māṁ tvāṁ prapannam ||", meaning: "Now I am confused about my duty and have lost all composure because of miserly weakness. In this condition I am asking You to tell me for certain what is best for me. Now I am Your disciple, and a soul surrendered unto You. Please instruct me.", lesson: "Surrender is the first step to receiving true wisdom. Admitting our confusion opens the door to divine guidance." },
    { verse: "2.11", sanskrit: "श्रीभगवानुवाच |\nअशोच्यानन्वशोचस्त्वं प्रज्ञावादांश्च भाषसे |\nगतासूनगतासूंश्च नानुशोचन्ति पण्डिताः ||", transliteration: "śhrī-bhagavān uvācha |\naśhochyān anvaśhochas tvaṁ prajñā-vādāṅśh cha bhāṣhase |\ngatāsūn agatāsūṅśh cha nānuśhochanti pण्डिताः ||", meaning: "The Supreme Lord said: While you speak words of wisdom, you are mourning for that which is not worthy of grief. The wise lament neither for the living nor for the dead.", lesson: "Transcend superficial emotions. Deep wisdom allows you to face life's transitions with a calm and centered perspective." },
    { verse: "2.12", sanskrit: "न त्वेवाहं जातु नासं न त्वं नेमे जनाधिपाः |\nन चैव न भविष्यामः सर्वे वयमतः परम् ||", transliteration: "na tvevāhaṁ jātu nāsaṁ na tvaṁ neme janādhipāḥ |\nna chaiva na भविष्यामः सर्वे वयमतः परम् ||", meaning: "Never was there a time when I did not exist, nor you, nor all these kings; nor in the future shall any of us cease to be.", lesson: "Individual consciousness is eternal. Our current identity is a temporary ripple in the ocean of existence." },
    { verse: "2.13", sanskrit: "देहिनोऽस्मिन्यथा देहे कौमारं यौवनं जरा |\nतथा देहान्तरप्राप्तिर्धीरस्तत्र न मुह्यति ||", transliteration: "dehino ’smin yathā dehe kaumāraṁ yauvanaṁ jarā |\ntathā dehāntara-prāptir dhīras tatra na muhyati ||", meaning: "As the embodied soul continuously passes, in this body, from boyhood to youth to old age, the soul similarly passes into another body at death. A sober person is not bewildered by such a change.", lesson: "Embrace the cycles of life. Just as we don't mourn the loss of childhood when we become adults, we shouldn't fear the transition of death." },
    { verse: "2.14", sanskrit: "मात्रास्पर्शास्तु कौन्तेय शीतोष्णसुखदुःखदाः |\nआगमापायिनोऽनित्यास्तांस्तितिक्षस्व भारत ||", transliteration: "mātrā-sparśhās tu kaunteya śhītoṣhṇa-sukha-duḥkha-dāḥ |\nāgamāpāyino ’nityās tāns titikṣhaswa bhārata ||", meaning: "O son of Kunti, the nonpermanent appearance of happiness and distress, and their disappearance in due course, are like the appearance and disappearance of winter and summer seasons. They arise from sense perception, O scion of Bharata, and one must learn to tolerate them without being disturbed.", lesson: "Develop resilience. Emotional highs and lows are as temporary as the weather; don't let them dictate your inner state." },
    { verse: "2.16", sanskrit: "नासतो विद्यते भावो नाभावो विद्यते सतः |\nउभयोरपि दृष्टोऽन्तस्त्वनयोस्तत्त्वदर्शिभिः ||", transliteration: "nāsato विद्यते भावो नाभावो विद्यते सतः |\nubhayor api dṛiṣhṭo ’ntas tvanayos tattva-darśhibhiḥ ||", meaning: "Of the nonexistent there is no endurance, and of the eternal there is no change. This has been concluded by those who are the seers of the truth.", lesson: "Identify with the eternal. Your physical state changes, but your essence remains. Focusing on the permanent reduces anxiety." },
    { verse: "2.20", sanskrit: "न जायते म्रियते वा कदाचि\nन्नायं भूत्वा भविता वा न भूयः |\nअजो नित्यः शाश्वतोऽयं पुराणो\nन हन्यते हन्यमाने शरीरे ||", transliteration: "na jāyate mriyate vā kadāchin\nnāyaṁ bhūtvā bhavitā vā nā bhūyaḥ |\najo nityaḥ śhāśhvato ’yaṁ purāṇo\nna hanyate hanyamāne śharīre ||", meaning: "The soul is never born, nor does it ever die. It is unborn, eternal, ever-existing, undying and primeval. It is not slain when the body is slain.", lesson: "Connect with your eternal essence. This realization provides ultimate security in an ever-changing world." },
    { verse: "2.22", sanskrit: "वासांसि जीर्णानि यथा विहाय\nनवानि गृह्णाति नरोऽपराणि |\nतथा शरीराणि विहाय जीर्णा\nन्यन्यानि संयाति नवानि देही ||", transliteration: "vāsāṁsi jīrṇāni yathā vihāya\nnavāni gṛihṇāti naro ’parāṇi |\ntathā śharīrāṇi vihāya jīrṇāny\nanyāni saṁyāti navāni dehī ||", meaning: "As a person puts on new garments, giving up old ones, the soul similarly accepts new material bodies, giving up the old and useless ones.", lesson: "Death is merely a transition. Viewing it as a change of clothes removes the fear and allows us to focus on the soul's progress." },
    { verse: "2.23", sanskrit: "नैनं छिन्दन्ति शस्त्राणि नैनं दहति पावकः |\nन चैनं क्लेदयन्त्यापो न शोषयति मारुतः ||", transliteration: "nainaṁ chhindanti śhastrāṇi nainaṁ dahati pāvakaḥ |\nna chainaṁ kledayanty āpo na śhoṣhayati mārutaḥ ||", meaning: "The soul can never be cut to pieces by any weapon, nor burned by fire, nor moistened by water, nor withered by the wind.", lesson: "You are invulnerable at your core. The external world can affect your circumstances but never your true self." },
    { verse: "2.24", sanskrit: "अच्छेद्योऽयमदाह्योऽयमक्लेद्योऽशोषय एव च |\nनित्यः सर्वगतः स्थाणुरचलोऽयं सनातनः ||", transliteration: "achchhedyo ’yam adāhyo ’yam akledyo ’śhoṣhya eva cha |\nnityaḥ sarva-gataḥ sthāṇur achalo ’yaṁ sanātanaḥ ||", meaning: "This soul is unbreakable and insoluble, and can be neither burned nor dried. He is everlasting, omnipresent, unchangeable, immovable and eternally the same.", lesson: "Stability in Spirit. Your true nature is the only thing in the universe that is truly constant." },
    { verse: "2.31", sanskrit: "स्वधर्ममपि चावेक्ष्य न विकम्पितुमर्हसि |\nधर्म्याद्धि युद्धाच्छ्रेयोऽन्यत्क्षत्रियस्य न विद्यते ||", transliteration: "swa-dharmam api chāvekṣhya na vikampitum arhasi |\ndharmyād dhi yuddhāch chhreyo ’nyat kṣhatriyasya na vidyate ||", meaning: "Considering your specific duty as a warrior, you should not waver. For a warrior, there is no better engagement than fighting for upholding righteousness.", lesson: "Honor your role. Fulfillment comes from aligning your actions with your nature and the needs of justice." },
    { verse: "2.38", sanskrit: "सुखदुःखे समे कृत्वा लाभालाभौ जयाजयौ |\nततो युद्धाय युज्यस्व नैवं पापमवाप्स्यसि ||", transliteration: "sukha-duḥkhe same kṛitvā lābhālābhau jayājayau |\ntato yuddhāya yujyaswa naivaṁ pāpam avāpsyasi ||", meaning: "Fight for the sake of fighting, without considering happiness or distress, loss or gain, victory or defeat—and by so doing you shall never incur sin.", lesson: "Action without calculation. When duty is performed for its own sake, the results lose their power to bind us." },
    { verse: "2.40", sanskrit: "नेहाभिक्रमनाशोऽस्ति प्रत्यवायो न विद्यते |\nस्वल्पमप्यस्य धर्मस्य त्रायते महतो भयात् ||", transliteration: "nehābhikrama-nāśho ’sti pratyavāyo na vidyate |\nswalpam apy asya dharmasya trāyate mahato bhayāt ||", meaning: "In this endeavor there is no loss or diminution, and a little advancement on this path can protect one from the most dangerous type of fear.", lesson: "Spiritual interest is eternal capital. Every effort toward consciousness is permanently credited to your soul." },
    { verse: "2.41", sanskrit: "व्यवसायात्मिका बुद्धिरेकेह कुरुनन्दन |\nबहुशाखा ह्यनन्ताश्च बुद्धयोऽव्यवसायिनाम् ||", transliteration: "vyavasāyātmikā buddhir ekeha kuru-nandana |\nbahu-śhākhā hyanantāśh cha buddhayo ’vyavasāyinām ||", meaning: "Those who are on this path are resolute in purpose, and their aim is one. O beloved child of the Kurus, the intelligence of those who are irresolute is many-branched and endless.", lesson: "Focus is power. A scattered mind achieves little; a concentrated mind penetrates the deepest mysteries." },
    { verse: "2.45", sanskrit: "त्रैगुण्यविषया वेदा निस्त्रैगुण्यो भवार्जुन |\nनिर्द्वन्द्वो नित्यसत्त्वस्थो निर्योगक्षेम आत्मवान् ||", transliteration: "trai-guṇya-viṣhayā vedā nistrai-guṇyo bhavārjuna |\nnirdwandwo nitya-sattva-stho niryoga-kṣhema ātmavān ||", meaning: "The Vedas deal mainly with the subject of the three modes of material nature. Rise above these modes, O Arjuna. Be free from all dualities and from all anxieties for gain and safety, and be established in the Self.", lesson: "Transcend the transactional. True freedom is found when you stop worrying about maintaining your status and start dwelling in your soul." },
    { verse: "2.47", sanskrit: "कर्मण्येवाधिकारस्ते मा फलेषु कदाचन |\nमा कर्मफलहेतुर्भूर्मा ते सङ्गोऽस्त्वकर्मणि ||", transliteration: "karmaṇy-evādhikāras te mā phaleṣhu kadāchana |\nmā karma-phala-hetur bhūr mā te saṅgo ’stv-akarmaṇi ||", meaning: "You have a right to perform your prescribed duties, but you are not entitled to the fruits of your actions. Never consider yourself to be the cause of the results of your activities, and never be attached to inaction.", lesson: "Master the art of 'Process over Result'. Excellence comes from total absorption in the task at hand, free from the anxiety of outcomes." },
    { verse: "2.48", sanskrit: "योगस्थः कुरु कर्माणि सङ्गं त्यक्त्वा धनञ्जय |\nसिद्ध्यसिद्ध्योः समो भूत्वा समत्वं योग उच्यते ||", transliteration: "yoga-sthaḥ kuru karmāṇi saṅgaṁ tyaktvā dhanañjaya |\nsiddhy-asiddhyoḥ samo bhūtvā samatvaṁ yoga uchyate ||", meaning: "Perform your duty equipoised, O Arjuna, abandoning all attachment to success or failure. Such equanimity is called yoga.", lesson: "Yoga is balance. True success is not winning, but maintaining your composure regardless of the result." },
    { verse: "2.49", sanskrit: "दूरेण ह्यवरं कर्म बुद्धियोगाद्धनञ्जय |\nबुद्धौ शरणमन्विच्छ कृपणाः फलहेतवः ||", transliteration: "dūreṇa hy avaraṁ karma buddhi-yogād dhanañjaya |\nbuddhau śharaṇam anvichchha kṛipaṇāḥ phala-hetavaḥ ||", meaning: "O Dhananjaya, keep all abominable activities far distant by devotional service, and in that consciousness surrender unto the Lord. Those who want to enjoy the fruits of their work are misers.", lesson: "Elevation of Motive. Move from 'What can I get?' to 'What can I contribute?'. Misery is the shadow of greed." },
    { verse: "2.50", sanskrit: "बुद्धियुक्तो जहातीह उभे सुकृतदुष्कृते |\nतस्माद्योगाय युज्यस्व योगः कर्मसु कौशलम् ||", transliteration: "buddhi-yukto jahātīha ubhe sukṛita-duṣhkṛite |\ntasmād yogāya yujyaswa yogaḥ कर्मसु कौशलम् ||", meaning: "A man engaged in devotional service rids himself of both good and bad actions even in this life. Therefore strive for yoga, which is the art of all work.", lesson: "Efficiency through spirit. When your mind is clear and detached, your work naturally becomes more skillful and perfect." },
    { verse: "2.51", sanskrit: "कर्मजं बुद्धियुक्ता हि फलं त्यक्त्वा मनीषिणः |\nजन्मबन्धविनिर्मुक्ताः पदं गच्छन्त्यनामयम् ||", transliteration: "karma-jaṁ buddhi-yuktā hi phalaṁ tyaktvā manīṣhiṇaḥ |\njanma-bandha-vinirmuktāḥ padaṁ gachchha nty anāmayam ||", meaning: "By thus engaging in devotional service to the Lord, great sages or devotees free themselves from the results of work in the material world. In this way they become free from the cycle of birth and death and attain the state beyond all miseries.", lesson: "Freedom from Karma. The 'weight' of life's consequences is lifted when actions are performed in a spirit of sacrifice." },
    { verse: "2.54", sanskrit: "अर्जुन उवाच |\nस्थितप्रज्ञस्य का भाषा समाधिस्थस्य केशव |\nस्थितधीः किं प्रभाषेत किमासीत व्रजेत किम् ||", transliteration: "arjuna uvācha |\nsthita-prajñasya kā bhāṣhā samādhi-sthasya keśhava |\nsthita-dhīḥ kiṁ prabhāṣheta kim āsīta vrajeta kim ||", meaning: "Arjuna said: O Krishna, what are the symptoms of one whose consciousness is thus merged in transcendence? How does he speak, and what is his language? How does he sit, and how does he walk?", lesson: "Wisdom is visible in behavior. Spirituality is not just a theory; it is a way of carrying oneself in the world." },
    { verse: "2.56", sanskrit: "दुःखेष्वनुद्विग्नमनाः सुखेषु विगतस्पृहः |\nवीतरागभयक्रोधः स्थितधीर्मुनिरुच्यते ||", transliteration: "duḥkheṣhv-anudvigna-manāḥ sukheṣhu vigata-spṛihaḥ |\nvīta-rāga-bhaya-krodhaḥ sthita-dhīr munir uchyate ||", meaning: "One whose mind is undisturbed even amidst misery, who does not crave happiness, and who is free from attachment, fear, and anger, is called a sage of steady intellect.", lesson: "Inner stability is the hallmark of wisdom. Aim to be the calm center of the storm." },
    { verse: "2.62", sanskrit: "ध्यायतो विषयान्पुंसः सङ्गस्तेषूपजायते |\nसङ्गात्सञ्जायते कामः कामात्क्रोधोऽभिजायते ||", transliteration: "dhyāyato viṣhayān puṁsaḥ saṅgas teṣhūpajāyate |\nsaṅgāt sañjāyate kāmaḥ kāmāt krodho ’bhijayate ||", meaning: "While contemplating on the objects of the senses, one develops attachment to them. Attachment leads to desire, and from desire arises anger.", lesson: "The slippery slope of desire. It starts with a simple thought and ends in loss of control. Guard your mind's focus." },
    { verse: "2.63", sanskrit: "क्रोधाद्भवति सम्मोहः सम्मोहात्स्मृतिविभ्रमः |\nस्मृतिभ्रंशाद्बुद्धिनाशो बुद्धिनाशात्प्रणश्यति ||", transliteration: "krodhād bhavati sammohaḥ sammohāt smṛiti-vibhramaḥ |\nsmṛiti-bhranśhād buddhi-nāśho buddhi-nāśhāt praṇaśhyati ||", meaning: "From anger comes complete delusion, and from delusion bewilderment of memory. When memory is bewildered, intelligence is lost, and when intelligence is lost one falls down again into the material pool.", lesson: "Anger is the enemy of reason. Never make decisions when your temper is high, for your intelligence is temporarily blinded." },
    { verse: "2.69", sanskrit: "या निशा सर्वभूतानां तस्यां जागर्ति संयमी |\nयस्यां जाग्रति भूताणि सा निशा पश्यतो मुनेः ||", transliteration: "yā niśhā sarva-bhūtānāṁ tasyāṁ jāgarti saṁyamī |\nyasyāṁ jāgrati bhūtāni sā niśhā paśhyato muneḥ ||", meaning: "What is night for all beings is the time of awakening for the self-controlled; and the time of awakening for all beings is night for the introspective sage.", lesson: "Different Realities. The 'wise' are awake to things the 'worldly' ignore (spirit, peace), and asleep to things the 'worldly' chase (ego, greed)." },
    { verse: "2.71", sanskrit: "विहाय कामान्यः सर्वान्पुमांश्चरति निःस्पृहः |\nनिर्ममो निरहङ्कारः स शान्तिमधिगच्छति ||", transliteration: "vihāya kāmān yaḥ sarvān pumānśh charati niḥspṛihaḥ |\nnirmamo nirahankāraḥ sa śhāntim adhigachchhati ||", meaning: "A person who has given up all desires for sense gratification, who lives free from desires, who has given up all sense of proprietorship and is devoid of false ego—he alone can attain real peace.", lesson: "Peace is the subtraction of ego. The less 'I' and 'Mine' there is, the more peace there is." },
    { verse: "2.72", sanskrit: "एषा ब्राह्मी स्थितिः पार्थ नैनां प्राप्य विमुह्यति |\nस्थित्वास्यामन्तकालेऽपि ब्रह्मनिर्वाणमृच्छति ||", transliteration: "eṣhā brāhmī sthitiḥ pārtha naināṁ prāpye vimuhyati |\nsthitvāsyām anta-kāle ’pi brahma-nirvāṇam ṛichchhati ||", meaning: "That is the way of the spiritual and godly life, after attaining which a man is not bewildered. If one is thus situated even at the hour of death, one can enter into the kingdom of God.", lesson: "The Final Goal. Establishing yourself in truth today ensures a clear and fearless transition tomorrow." }
  ]
};
