import { Chapter } from './types';

export const ch3: Chapter = {
  id: 3,
  name: "Karma Yoga",
  meaning: "The Yoga of Action",
  slokas_count: 43,
  summary: "Krishna explains that action is unavoidable and that the key is to perform one's duties as a sacrifice, without ego or expectation of reward.",
  themes: ["Selfless Service", "Sacrifice", "Leadership by Example", "Duty"],
  featured_verse: "3.21",
  slokas: [
    { verse: "3.1", sanskrit: "अर्जुन उवाच |\nज्यायसी चेत्कर्मणस्ते मता बुद्धिर्जनार्दन |\nतत्किं कर्मणि घोरे मां नियोजयसि केशव ||", transliteration: "arjuna uvācha |\njyāyasī chet karmaṇas te matā buddhir janārdana |\ntat kiṁ karmaṇi ghore māṁ niyojayasi keśhava ||", meaning: "Arjuna said: O Janardana, if You consider knowledge superior to action, then why do You urge me to engage in this ghastly war, O Keshav?", lesson: "Ask for clarity. Confusion often arises when we perceive a conflict between spiritual study and physical duty." },
    { verse: "3.4", sanskrit: "न कर्मणामनारम्भान्नैष्कर्म्यं पुरुषोऽश्नुते |\nन च संन्यसनादेव सिद्धिं समधिगच्छति ||", transliteration: "na karmaṇām anārambhān naiṣhkarmyaṁ puruṣho ’śhnute |\nna cha sannyasanād eva siddhiṁ samadhigachchhati ||", meaning: "Not by merely abstaining from work can one achieve freedom from reaction, nor by renunciation alone can one attain perfection.", lesson: "No shortcuts. Spirituality is found *through* your work, not by running away from it." },
    { verse: "3.5", sanskrit: "न हि कश्चित्क्षणमपि जातु तिष्ठत्यकर्मकृत् |\nकार्यते ह्यवशः कर्म सर्वः प्रकृतिजैर्गुणैः ||", transliteration: "na hi kaśhchit kṣhaṇam api jātu tiṣhṭhatyakarmakṛit |\nkāryate hyavaśhaḥ karma sarvaḥ prakṛitijair guṇaiḥ ||", meaning: "Everyone is forced to act helplessly according to the qualities he has acquired from the modes of material nature; therefore no one can refrain from doing something, not even for a moment.", lesson: "Accept the Law of Action. Since you must act, learn to act with purpose rather than being a puppet of nature." },
    { verse: "3.8", sanskrit: "नियतं कुरु कर्म त्वं कर्म ज्यायो ह्यकर्मणः |\nशरीरयात्रापि च ते न प्रसिद्ध्येदकर्मणः ||", transliteration: "niyataṁ kuru karma tvaṁ karma jyāyo hyakarmaṇaḥ |\nśharīra-yātrāpi cha te na prasiddhyed akarmaṇaḥ ||", meaning: "Perform your prescribed duty, for doing so is better than not working. One cannot even maintain one's physical body without work.", lesson: "Honor your responsibilities. Work is the engine of life; perform it with integrity." },
    { verse: "3.9", sanskrit: "यज्ञार्थात्कर्मणोऽन्यत्र लोकोऽयं कर्मबन्धनः |\nतदर्थं कर्म कौन्तेय मुक्तसङ्गः समाचर ||", transliteration: "yajñārthāt karmaṇo ’nyatra loko ’yaṁ karma-bandhanaḥ |\ntad-arthaṁ karma kaunteya mukta-saṅgaḥ samāchara ||", meaning: "Work must be performed as a sacrifice to God, otherwise work causes bondage in this material world. Therefore, O son of Kunti, perform your prescribed duties for His satisfaction, and in that way you will always remain free from attachment and bondage.", lesson: "Sacrifice (Yajna). Transform routine work into a sacred offering. When we work for a higher cause, the work itself becomes a path to freedom." },
    { verse: "3.10", sanskrit: "सहयज्ञाः प्रजाः सृष्ट्वा पुरोवाच प्रजापतिः |\nअनेन प्रसविष्यध्वमेष वोऽस्त्विष्टकामधुक् ||", transliteration: "saha-yajñāḥ prajāḥ sṛiṣhṭvā purovācha prajāpatiḥ |\nanena prasaviṣhyadhvam eṣha vo ’stv iṣhṭa-kāma-dhuk ||", meaning: "In the beginning of creation, the Lord of all creatures sent forth generations of men and demigods, along with sacrifices for Vishnu, and blessed them by saying, 'Be thou happy by this sacrifice because its performance will bestow upon you everything desirable for living happily and achieving liberation.'", lesson: "Universal Reciprocity. The universe is a system of giving and receiving. Success comes when we contribute our part." },
    { verse: "3.13", sanskrit: "यज्ञशिष्टाशिनः सन्तो मुच्यन्ते सर्वकिल्बिषैः |\nभुञ्जते ते त्वघं पापा ये पचन्त्यात्मकारणात् ||", transliteration: "yajña-śhiṣhṭāśhinaḥ santo muchyante sarva-kilbiṣhaiḥ |\nbhuñjate te tv aghaṁ pāpā ye pachanty ātma-kāraṇāt ||", meaning: "The devotees of the Lord are released from all kinds of sins because they eat food which is offered first for sacrifice. Others, who prepare food for personal sense enjoyment, verily eat only sin.", lesson: "Sanctified consumption. Be grateful for your resources and use them to serve others first; this purifies your existence." },
    { verse: "3.19", sanskrit: "तस्मादसक्तः सततं कार्यं कर्म समाचर |\nअसक्तो ह्याचरन्कर्म परमाप्नोति पूरुषः ||", transliteration: "tasmād asaktaḥ satataṁ kāryaṁ karma samāchara |\nasakto hyācharan karma param āpnoti pūruṣhaḥ ||", meaning: "Therefore, without being attached to the fruits of activities, one should act as a matter of duty, for by working without attachment one attains the Supreme.", lesson: "Process over Outcome. Detached action is the fastest path to spiritual evolution." },
    { verse: "3.20", sanskrit: "कर्मणैव हि संसिद्धिमास्थिता जनकादयः |\nलोकसंग्रहमेवापि सम्पश्यन्कर्तुमर्हसि ||", transliteration: "karmaṇaiva hi saṁsiddhim āsthitā janakādayaḥ |\nloka-saṅgraham evāpi sampaśhyan kartum arhasi ||", meaning: "Kings such as Janaka attained perfection solely by performance of prescribed duties. Therefore, just for the sake of educating the people in general, you should perform your work.", lesson: "Social Welfare (Loka-sangraha). Your actions set a standard for society. Work excellently to inspire others." },
    { verse: "3.21", sanskrit: "यद्यदाचरति श्रेष्ठस्तत्तदेवेतरो जनः |\nस यत्प्रमाणं कुरुते लोकस्तदनुवर्तते ||", transliteration: "yad yad ācharati śhreṣhṭhas tat tad evetaro janaḥ |\nsa yat pramāṇaṁ kurute lokas tad anuvartate ||", meaning: "Whatever actions great people perform, common people follow. Whatever standards they set, the world pursues.", lesson: "The Power of Example. Leadership is not a rank but a responsibility to live the values you preach." },
    { verse: "3.27", sanskrit: "प्रकृतेः क्रियमाणानि गुणैः कर्माणि सर्वशः |\nअहङ्कारविमूढात्मा कर्ताहमिति मन्यते ||", transliteration: "prakṛiteḥ kriyamāṇāni guṇaiḥ karmāṇi sarvaśhaḥ |\nahaṅkāra-vimūḍhātmā kartāham iti manyate ||", meaning: "The spirit soul bewildered by the influence of false ego thinks himself the doer of activities that are in actuality carried out by the three modes of material nature.", lesson: "Release the 'Doer' Ego. Recognize that you are part of a larger cosmic system. Humility comes from seeing the big picture." },
    { verse: "3.30", sanskrit: "मयि सर्वाणि कर्माणि संन्यस्याध्यात्मचेतसा |\nनिराशीर्निर्ममो भूत्वा युध्यस्व विगतज्वरः ||", transliteration: "mayi sarvāṇi karmāṇi sannyasyādhyātma-chetasā |\nnirāśhīr nirmamo bhūtvā yudhyasva vigata-jvaraḥ ||", meaning: "Therefore, O Arjuna, surrendering all your works unto Me, with full knowledge of Me, without desires for profit, with no claims to proprietorship, and free from lethargy, fight.", lesson: "Vibrant Engagement. Give your 100% to your duty, but keep your heart anchored in the Divine." },
    { verse: "3.35", sanskrit: "श्रेयान्स्वधर्मो विगुणः परधर्मात्स्वनुष्ठितात् |\nस्वधर्मे निधनं श्रेयः परधर्मो भयावहः ||", transliteration: "śhreyān swa-dharmo viguṇaḥ para-dharmāt sv-anuṣhṭhitāt |\nswa-dharme nidhanaṁ śhreyaḥ para-dharmo bhayāvahaḥ ||", meaning: "It is far better to perform one's own duty, even if imperfectly, than to perform another's duty perfectly. Destruction in the course of performing one's own duty is better than the danger of following another's path.", lesson: "Authenticity. Your 'Swadharma' is your unique path. Don't trade your soul's calling for someone else's success." },
    { verse: "3.37", sanskrit: "श्रीभगवानुवाच |\nकाम एष क्रोध एष रजोगुणसमुद्भवः |\nमहाशनो महापाप्मा विद्ध्येनमिह वैरिणम् ||", transliteration: "śhrī-bhagavān uvācha |\nkāma eṣha krodha eṣha rajo-guṇa-samudbhavaḥ |\nmahāśhano mahā-pāpmā viddhy enam iha vairiṇam ||", meaning: "The Supreme Lord said: It is lust only, Arjuna, which is born of contact with the material mode of passion and later transformed into wrath, and which is the all-devouring sinful enemy of this world.", lesson: "Internal Enemy. Recognize that your greatest obstacles are your own untamed desires and anger." },
    { verse: "3.42", sanskrit: "इन्द्रियाणि पराण्याहुरिन्द्रियेभ्यः परं मनः |\nमनसस्तु परा बुद्धिर्यो बुद्धेः परतस्तु सः ||", transliteration: "indriyāṇi parāṇyāhur indriyebhyaḥ paraṁ manaḥ |\nmanasas tu parā buddhir yo buddheḥ paratas tu saḥ ||", meaning: "The working senses are superior to dull matter; mind is higher than the senses; intelligence is still higher than the mind; and he [the soul] is even higher than the intelligence.", lesson: "The Hierarchy of Self. Use your intelligence to govern your mind and senses, aligning them with your eternal soul." }
  ]
};