import { Chapter } from './types';

export const ch4: Chapter = {
  id: 4,
  name: "Jnana Karma Sanyasa Yoga",
  meaning: "The Yoga of Knowledge and Action",
  slokas_count: 42,
  summary: "Krishna reveals the secret of divine action and the importance of spiritual knowledge in purifying the mind and attaining liberation.",
  themes: ["Divine Incarnation", "Sacred Knowledge", "Purification", "Transcendental Vision"],
  featured_verse: "4.7",
  slokas: [
    { verse: "4.1", sanskrit: "श्रीभगवानुवाच |\nइमं विवस्वते योगं प्रोक्तवानहमव्ययम् |\nविवस्वान्मनवे प्राह मनुरिक्ष्वाकवेऽब्रवीत् ||", transliteration: "śhrī-bhagavān uvācha |\nimaṁ vivasvate yogaṁ proktavān aham avyayam |\nvivasvān manave prāha manur ikṣhvākave ’bravīt ||", meaning: "The Supreme Lord said: I taught this eternal science of Yoga to the Sun-god, Vivasvan, who taught it to Manu, the father of mankind, and Manu in turn taught it to Ikshvaku.", lesson: "Timeless Wisdom. The truths of the Gita are ancient and have guided leaders since the dawn of time." },
    { verse: "4.7", sanskrit: "यदा यदा हि धर्मस्य ग्लानिर्भवति भारत |\nअभ्युत्थानमधर्मस्य तदात्मानं सृजाम्यहम् ||", transliteration: "yadā yadā hi dharmasya glānir bhavati bhārata |\nabhyutthānam adharmasya tadātmānaṁ sṛijāmyaham ||", meaning: "Whenever there is a decline in righteousness and a rise in unrighteousness, O Bharat, then I manifest myself in the world.", lesson: "Divine Correction. Trust that when personal or global darkness peaks, a higher power intervenes to restore balance." },
    { verse: "4.8", sanskrit: "परित्राणाय साधूनां विनाशाय च दुष्कृताम् |\nधर्मसंस्थापनार्थाय सम्भवामि युगे युगे ||", transliteration: "paritrāṇāya sādhūnāṁ vināśhāya cha duṣhkṛitām |\ndharma-sansthāpanārthāya sambhavāmi yuge yuge ||", meaning: "To deliver the pious and to annihilate the miscreants, as well as to reestablish the principles of religion, I Myself appear, millennium after millennium.", lesson: "Justice is Eternal. Goodness is always protected in the grand arc of time." },
    { verse: "4.9", sanskrit: "जन्म कर्म च मे दिव्यमेवं यो वेत्ति तत्त्वतः |\nत्यक्त्वा देहं पुनर्जन्म नैति मामेति सोऽर्जुन ||", transliteration: "janma karma cha me divyam evaṁ yo vetti tattvataḥ |\ntyaktvā dehaṁ punar-janma naiti mām eti so ’rjuna ||", meaning: "One who knows the transcendental nature of My appearance and activities does not, upon leaving the body, take birth again in this material world, but attains My eternal abode, O Arjuna.", lesson: "Divine Connection. Understanding the Divine's work in the world frees your soul from the cycle of habitual rebirth." },
    { verse: "4.10", sanskrit: "वीतरागभयक्रोधा मन्मया मामुपाश्रिताः |\nबहवो ज्ञानतपसा पूता मद्भावमागताः ||", transliteration: "vīta-rāga-bhaya-krodhā man-mayā mām upāśhritāḥ |\nbahavo jñāna-tapasā pūtā mad-bhāvam āgatāḥ ||", meaning: "Being freed from attachment, fear and anger, being fully absorbed in Me and taking refuge in Me, many, many persons in the past became purified by knowledge of Me—and thus they all attained transcendental love for Me.", lesson: "Purification through Knowledge. Wisdom is the fire that burns away fear and anger, leaving only love." },
    { verse: "4.11", sanskrit: "ये यथा मां प्रपद्यन्ते तांस्तथैव भजाम्यहम् |\nमम वर्त्मानुवर्तन्ते मनुष्याः पार्थ सर्वशः ||", transliteration: "ye yathā māṁ prapadyante tāns tathaiva bhajāmy aham |\nmama vartmānuvartante manuṣhyāḥ pārtha sarvaśhaḥ ||", meaning: "As all surrender unto Me, I reward them accordingly. Everyone follows My path in all respects, O son of Pritha.", lesson: "The Law of Reciprocity. You receive from life exactly what you put into it. The Divine mirrors your sincerity." },
    { verse: "4.13", sanskrit: "चातुर्वर्ण्यं मया सृष्टं गुणकर्मविभागशः |\nतस्य कर्तारमपि मां विद्ध्यकर्तारमव्ययम् ||", transliteration: "chātur-varṇyaṁ mayā sṛiṣhṭaṁ guṇa-karma-vibhāgaśhaḥ |\ntasya kartāram api māṁ viddhy akartāram avyayam ||", meaning: "The four divisions of human society were created by Me according to the three modes of material nature and the work ascribed to them.", lesson: "Natural Talents. Everyone has a unique role based on their innate qualities. Respect your own nature and that of others." },
    { verse: "4.18", sanskrit: "कर्मण्यकर्म यः पश्येदकर्मणि च कर्म यः |\nस बुद्धिमान्मनुष्येषु स युक्तः कृत्स्नकर्मकृत् ||", transliteration: "karmaṇyakarma yaḥ paśhyed akarmaṇi cha karma yaḥ |\nsa buddhimān manuṣhyeṣhu sa yuktaḥ kṛitsna-karma-kṛit ||", meaning: "One who sees inaction in action, and action in inaction, is intelligent among men, and he is in the transcendental position, although engaged in all sorts of activities.", lesson: "Inner Stillness. Find a place of calm within your busiest day. Conversely, realize that 'doing nothing' is also an act with consequences." },
    { verse: "4.20", sanskrit: "त्यक्त्वा कर्मफलासङ्गं नित्यतृप्तो निराश्रयः |\nकर्मण्यभिप्रवृत्तोऽपि नैव किञ्चित्करोति सः ||", transliteration: "tyaktvā karma-phalāsaṅgaṁ nitya-tṛipto nirāśhrayaḥ |\nkarmaṇy abhipravṛitto ’pi naiva kiñchit karoti saḥ ||", meaning: "Abandoning all attachment to the results of his activities, ever satisfied and independent, he performs no fruitive action, although engaged in all kinds of undertakings.", lesson: "True Independence. When you stop depending on results for your happiness, you become truly free to work excellently." },
    { verse: "4.24", sanskrit: "ब्रह्मार्पणं ब्रह्म हविर्ब्रह्माग्नौ ब्रह्मणा हुतम् |\nब्रह्मैव तेन गन्तव्यं ब्रह्मकर्मसमाधिना ||", transliteration: "brahmārpaṇaṁ brahma havir brahmāgnau brahmaṇā hutam |\nbrahmaiva tena gantavyaṁ brahma-karma-samādhinā ||", meaning: "A person who is fully absorbed in Krishna consciousness is sure to attain the spiritual kingdom because of his full contribution to spiritual activities, in which the consummation is absolute and that which is offered is of the same spiritual nature.", lesson: "Sacred Vision. See every interaction as a divine offering. This transforms mundane life into a continuous meditation." },
    { verse: "4.33", sanskrit: "श्रेयान्द्रव्यमयाद्यज्ञाज्ज्ञानयज्ञः परन्तप |\nसर्वं कर्माखिलं पार्थ ज्ञाने परिसमाप्यते ||", transliteration: "śhreyān dravyamayād yajñāj jñāna-yajñaḥ parantapa |\nsarvaṁ karmākhilaṁ pārtha jñāne parisamāpyate ||", meaning: "O chastiser of the enemy, the sacrifice performed in knowledge is better than the mere sacrifice of material possessions. After all, O son of Pritha, all sacrifices of work culminate in transcendental knowledge.", lesson: "Knowledge is the Goal. Physical charity is good, but sharing or acquiring wisdom is the highest form of sacrifice." },
    { verse: "4.34", sanskrit: "तद्विद्धि प्रणिपातेन परिप्रश्नेन सेवया |\nउपदेक्ष्यन्ति ते ज्ञानं ज्ञानिनस्तत्त्वदर्शिनः ||", transliteration: "tad viddhi praṇipātena paripraśhnena sevayā |\nupadekṣhyanti te jñānaṁ jñāninas tattva-darśhinaḥ ||", meaning: "Just try to learn the truth by approaching a spiritual master. Inquire from him submissively and render service unto him. The enlightened souls can impart knowledge unto you because they have seen the truth.", lesson: "Humility in Learning. Real wisdom requires an open heart, honest questions, and a willingness to serve the teacher." },
    { verse: "4.36", sanskrit: "अपि चेदसि पापेभ्यः सर्वेभ्यः पापकृत्तमः |\nसर्वं ज्ञानप्लवेनैव वृजिनं सन्तरिष्यसि ||", transliteration: "api ched asi pāpebhyaḥ sarvebhyaḥ pāpa-kṛittamaḥ |\nsarvaṁ jñāna-plavenaiva vṛijinaṁ santariṣhyasi ||", meaning: "Even if you are considered the most sinful of all sinners, when you are situated in the boat of transcendental knowledge you will be able to cross over the ocean of miseries.", lesson: "Hope for All. No mistake is so big that wisdom cannot redeem it. Knowledge is the boat to safety." },
    { verse: "4.38", sanskrit: "न हि ज्ञानेन सदृशं पवित्रमिह विद्यते |\nतत्स्वयं योगसंसिद्धः कालेनात्मनि विन्दति ||", transliteration: "na hi jñānena sadṛiśhaṁ pavitram iha vidyate |\ntat svayaṁ yoga-saṁsiddhaḥ kālenātmani vindati ||", meaning: "In this world, there is nothing as purifying as transcendental knowledge. One who has become accomplished in Yoga finds this knowledge within the self in course of time.", lesson: "Internal Wisdom. Eventually, all your study leads you to the realization that the Truth is already within you." },
    { verse: "4.39", sanskrit: "श्रद्धावाँल्लभते ज्ञानं तत्परः संयतेन्द्रियः |\nज्ञानं लब्ध्वा परां शान्तिमचिरेणाधिगच्छति ||", transliteration: "śhraddhāvān labhate jñānaṁ tat-paraḥ saṁyatendriyaḥ |\njñānaṁ labdhvā parāṁ śhāntim achireṇādhigachchhati ||", meaning: "A faithful man who is dedicated to transcendental knowledge and who subdues his senses is eligible to achieve such knowledge, and having achieved it he quickly attains the supreme spiritual peace.", lesson: "Faith + Discipline = Peace. Calmness is the immediate reward for a mind fixed on the Truth." }
  ]
};