import { Chapter } from './types';

export const ch5: Chapter = {
  id: 5,
  name: "Karma Vairagya Yoga",
  meaning: "The Yoga of Renunciation",
  slokas_count: 29,
  summary: "Krishna reconciles the paths of action and renunciation, explaining that true renunciation is an internal state of detachment from results while remaining active in duty.",
  themes: ["Equality of Vision", "Detachment", "Internal Peace", "Renunciation"],
  featured_verse: "5.18",
  slokas: [
    { verse: "5.1", sanskrit: "अर्जुन उवाच |\nसंन्यासं कर्मणां कृष्ण पुनर्योगं च शंससि |\nयच्छ्रेय एतयोरेकं तन्मे ब्रूहि सुनिश्चितम् ||", transliteration: "arjuna uvācha |\nsannyāsaṁ karmaṇāṁ kṛiṣhṇa punar yogaṁ cha śhaṅsasi |\nyach chhreya etayor ekaṁ tan me brūhi su-niśhchitam ||", meaning: "Arjuna said: O Krishna, first of all You ask me to renounce work, and then again You recommend work with devotion. Now will You kindly tell me definitely which of the two is more beneficial?", lesson: "Clarity in choice. When faced with conflicting paths, seek the one that aligns most with your current capacity for action and focus." },
    { verse: "5.2", sanskrit: "श्रीभगवानुवाच |\nसंन्यासः कर्मयोगश्च निःश्रेयसकरावुभौ |\nतयोस्तु कर्मसंन्यासात्कर्मयोगो विशिष्यते ||", transliteration: "śhrī-bhagavān uvācha |\nsannyāsaḥ karma-yogaśh cha niḥśhreyasa-karāv ubhau |\ntayos tu karma-sannyāsāt karma-yogo viśhiṣhyate ||", meaning: "The Supreme Lord said: Both the renunciation of work and work in devotion are good for liberation; but of the two, working in devotional service is better than renunciation of work.", lesson: "Action over Inaction. It is easier and more effective to stay engaged in the world with the right attitude than to try to escape it prematurely." },
    { verse: "5.3", sanskrit: "ज्ञेयः स नित्यसंन्यासी यो न द्वेष्टि न काङ्क्षति |\nनिर्द्वन्द्वो हि महाबाहो सुखं बन्धात्प्रमुच्यते ||", transliteration: "jñeyaḥ sa nitya-sannyāsī yo na dveṣhṭi na kāṅkṣhati |\nnirdwandwo hi mahā-bāho sukhaṁ bandhāt pramuchyate ||", meaning: "One who neither hates nor desires the fruits of his activities is known to be always renounced. Such a person, liberated from all dualities, easily overcomes material bondage and is completely liberated.", lesson: "Internal Renunciation. True freedom is not about where you live, but about being free from the push and pull of likes and dislikes." },
    { verse: "5.7", sanskrit: "योगयुक्तो विशुद्धात्मा विजितात्मा जितेन्द्रियः |\nसर्वभूतात्मभूतात्मा कुर्वन्नपि न लिप्यते ||", transliteration: "yoga-yukto viśhuddhātmā vijitātmā jitendriyaḥ |\nsarva-bhūtātma-bhūtātmā kurvann api na lipyate ||", meaning: "One who works in devotion, who is a pure soul, and who controls his mind and senses is dear to everyone, and everyone is dear to him. Though always working, such a man is never entangled.", lesson: "Self-Mastery. When you govern your senses and act with purity, your actions leave no negative traces on your soul." },
    { verse: "5.10", sanskrit: "ब्रह्मण्याधाय कर्माणि सङ्गं त्यक्त्वा करोति यः |\nलिप्यते न स पापेन पद्मपत्रमिवाम्भसा ||", transliteration: "brahmaṇyādhāya karmāṇi saṅgaṁ tyaktvā karoti yaḥ |\nlipyate na sa pāpena padma-patram ivāmbhasā ||", meaning: "One who performs his duty without attachment, surrendering the results unto the Supreme Lord, is unaffected by sinful action, as the lotus leaf is untouched by water.", lesson: "The Lotus Effect. Be present in the world, but remain mentally detached from the greed and chaos that surround you." },
    { verse: "5.11", sanskrit: "कायेन मनसा बुद्ध्या केवलैरिन्द्रियैरपि |\nयोगिनः कर्म कुर्वन्ति सङ्गं त्यक्त्वात्मशुद्धये ||", transliteration: "kāyena manasā buddhyā kevalair indriyair api |\nyoginaḥ karma kurvanti saṅgaṁ tyaktvātma-śhuddhaye ||", meaning: "The yogis, abandoning attachment, act with body, mind, intelligence and even with the senses, only for the purpose of purification.", lesson: "Work as Therapy. View every task as an opportunity to clean the 'mirror' of your mind, rather than just a way to get ahead." },
    { verse: "5.18", sanskrit: "विद्याविनयसम्पन्ने ब्राह्मणे गवि हस्तिनि |\nशुनि चैव श्वपाके च पण्डिताः समदर्शिनः ||", transliteration: "vidyā-vinaya-sampanne brāhmaṇe gavi hastini |\nśhuni chaiva śhva-pāke cha paṇḍitāḥ sama-darśhinaḥ ||", meaning: "The truly learned, with the eyes of divine knowledge, see with equal vision a gentle Brahmin, a cow, an elephant, a dog, and a dog-eater.", lesson: "Universal Empathy. Look past the 'labels' and 'packaging' of life to recognize the same spark of life in every being." },
    { verse: "5.19", sanskrit: "इहैव तैर्जितः सर्गो येषां साम्ये स्थितं मनः |\nनिर्दोषं हि समं ब्रह्म तस्माद्ब्रह्मणि ते स्थिताः ||", transliteration: "ihaiva tair jitaḥ sargo yeṣhāṁ sāmye sthitaṁ manaḥ |\nnirdoṣhaṁ hi samaṁ brahma tasmād brahmaṇi te sthitāḥ ||", meaning: "Those whose minds are established in sameness and equanimity have already conquered the conditions of birth and death. They are flawless like Brahman, and thus they are already situated in Brahman.", lesson: "Conquer Life through Balance. Inner peace is not a future goal; it is the immediate result of a mind that stays steady." },
    { verse: "5.21", sanskrit: "बाह्यस्पर्शेष्वसक्तात्मा विन्दत्यात्मनि यत्सुखम् |\nस ब्रह्मयोगयुक्तात्मा सुखमक्षयमश्नुते ||", transliteration: "bāhya-sparśheṣhv asaktātmā vindaty ātmani yat sukham |\nsa brahma-yoga-yuktātmā sukham akṣhayam aśhnute ||", meaning: "Such a liberated person is not attracted to material sense pleasure but is always in trance, enjoying the pleasure within. In this way the self-realized person enjoys unlimited happiness, for he concentrates on the Supreme.", lesson: "Inner Joy. Stop looking for happiness in things; you are already carrying a fountain of joy within your own spirit." },
    { verse: "5.22", sanskrit: "ये हि संस्पर्शजा भोगा दुःखयोनय एव ते |\nआद्यन्तवन्तः कौन्तेय न तेषु रमते बुधः ||", transliteration: "ye hi saṁsparśha-jā bhogā duḥkha-yonaya eva te |\nādy-antavantaḥ kaunteya na teṣhu ramate budhaḥ ||", meaning: "An intelligent person does not take part in the sources of misery, which are due to contact with the material senses. O son of Kunti, such pleasures have a beginning and an end, and so the wise man does not delight in them.", lesson: "Avoid Temporary Highs. Recognize that pleasures which depend on the senses always end in a 'crash'; seek the joy that is independent of things." },
    { verse: "5.24", sanskrit: "योऽन्तःसुखोऽन्तरारामस्तथान्तर्ज्योतिरेव यः |\nस योगी ब्रह्मनिर्वाणं ब्रह्मभूतोऽधिगच्छति ||", transliteration: "yo ’ntaḥ-sukho ’ntar-ārāmas tathāntar-jyotir eva yaḥ |\nsa yogī brahma-nirvāṇaṁ brahma-bhūto ’dhigachchhati ||", meaning: "One whose happiness is within, who is active and rejoices within, and whose aim is inward is actually the perfect mystic. He is liberated in the Supreme, and ultimately he attains the Supreme.", lesson: "Inward Focus. The highest success is being comfortable and happy in your own company, guided by your inner light." },
    { verse: "5.29", sanskrit: "भोक्तारं यज्ञतपसां सर्वलोकमहेश्वरम् |\nसुहृदं सर्वभूतानां ज्ञात्वा मां शान्तिमृच्छति ||", transliteration: "bhoktāraṁ yajña-tapasāṁ sarva-loka-maheśhwaram |\nsuhṛidaṁ sarva-bhūtānāṁ jñātvā māṁ śhāntim ṛichchhati ||", meaning: "A person in full consciousness of Me, knowing Me to be the ultimate beneficiary of all sacrifices and austerities, the Supreme Lord of all planets and demigods, and the benefactor and well-wisher of all living entities, attains peace from the pangs of material miseries.", lesson: "Universal Friendship. Trust that the universe is your best friend. When you realize the Source cares for you, all anxiety vanishes." }
  ]
};