import { Chapter } from './types';

export const ch6: Chapter = {
  id: 6,
  name: "Abhyasa Yoga",
  meaning: "The Yoga of Meditation",
  slokas_count: 47,
  summary: "Krishna provides detailed instructions on the practice of meditation (Dhyana) and explains the importance of controlling the mind.",
  themes: ["Self-Mastery", "Discipline", "Meditation", "Moderation"],
  featured_verse: "6.5",
  slokas: [
    { verse: "6.1", sanskrit: "श्रीभगवानुवाच |\nअनाश्रितः कर्मफलं कार्यं कर्म करोति यः |\nस संन्यासी च योगी च न निरग्निर्न चाक्रियः ||", transliteration: "śhrī-bhagavān uvācha |\nanāśhritaḥ karma-phalaṁ kāryaṁ karma karoti yaḥ |\nsa sannyāsī cha yogī cha na niragnir na chākriyaḥ ||", meaning: "The Supreme Lord said: One who is unattached to the fruits of his work and who works as he is obligated is in the renounced order of life, and he is the true mystic, not he who lights no fire and performs no duty.", lesson: "Duty as Meditation. You don't have to quit society to be a 'Yogi'; just quit your attachment to being the center of attention." },
    { verse: "6.5", sanskrit: "उद्धरेदात्मनात्मानं नात्मानमवसादयेत् |\nआत्मैव ह्यात्मनो बन्धुरात्मैव रिपुरात्मनः ||", transliteration: "uddhared ātmanātmānaṁ nātmānam avasādayet |\nātmaiva hyātmano bandhur ātmaiva ripur ātmanaḥ ||", meaning: "Elevate yourself through the power of your mind, and do not degrade yourself. For the mind can be your greatest friend and also your worst enemy.", lesson: "Mental Responsibility. You are the architect of your own happiness or misery based on how you train your thoughts." },
    { verse: "6.6", sanskrit: "बन्धुरात्मात्मनस्तस्य yeनात्मैवात्मना जितः |\nअनात्मनस्तु शत्रुत्वे वर्तेतात्मैव शत्रुवत् ||", transliteration: "bandhur ātmātmanas tasya yenātmaivātmanā jitaḥ |\nanātmanas tu śhatrutve vartetātmaiva śhatru-vat ||", meaning: "For those who have conquered the mind, it is their best friend. For those who have failed to do so, the mind stays as their greatest enemy.", lesson: "Self-Conquest. A disciplined mind provides clarity and peace; an unruly one creates constant internal war." },
    { verse: "6.10", sanskrit: "योगी युञ्जीत सततमात्मानं रहसि स्थितः |\nएकाकी यतचित्तात्मा निराशीरपरिग्रहः ||", transliteration: "yogī yuñjīta satatam ātmānaṁ rahasi sthitaḥ |\nekākī yata-chittātmā nirāśhīr aparigrahaḥ ||", meaning: "A transcendentalist should always engage his body, mind and self in relationship with the Supreme; he should live alone in a secluded place and should always carefully control his mind. He should be free from desires and feelings of possessiveness.", lesson: "The Value of Solitude. Regular 'quiet time' is essential for spiritual mental health. Detach from the noise of the world to hear your soul." },
    { verse: "6.16", sanskrit: "नात्यश्नतस्तु योगोऽस्ति न चैकान्तमनश्नतः |\nन चातिस्वप्नशीलस्य जाग्रतो नैव चार्जुन ||", transliteration: "nātyaśhnatas tu yogo ’sti na chaikāntam anaśhnataḥ |\nna chāti-swapna-śhīlasya jāgrato naiva chārjuna ||", meaning: "There is no possibility of one's becoming a yogi, O Arjuna, if one eats too much or eats too little, sleeps too much or does not sleep enough.", lesson: "Balance. Spiritual life is about mindful moderation in all physical habits. Extremes are barriers to progress." },
    { verse: "6.17", sanskrit: "युक्ताहारविहारस्य युक्तचेष्टस्य कर्मसु |\nयुक्तस्वप्नावबोधस्य योगो भवति दुःखहा ||", transliteration: "yuktāhāra-vihārasya yukta-cheṣhṭasya karmasu |\nyukta-swapnāvabodhasya yogo bhavati duḥkha-hā ||", meaning: "He who is regulated in his habits of eating, sleeping, recreation and work can mitigate all material pains by practicing the yoga system.", lesson: "The Middle Path. Consistent, healthy habits are the foundation for a pain-free and joyful life." },
    { verse: "6.19", sanskrit: "यथा दीपो निवातस्थो नेङ्गते सोपमा स्मृता |\nयोगिनो यतचित्तस्य युञ्जतो योगमात्मनः ||", transliteration: "yathā dīpo nivāta-stho neṅgate sopamā smṛitā |\nyogino yata-chittasya yuñjato yogam ātmanaḥ ||", meaning: "As a lamp in a windless place does not waver, so the transcendentalist, whose mind is subdued, remains always steady in his meditation on the transcendent Self.", lesson: "Steadfastness. Strive for a mind that is not shaken by the 'winds' of gossip, fear, or sensory cravings." },
    { verse: "6.24", sanskrit: "सङ्कल्पप्रभवान्कामांस्त्यक्त्वा सर्वानशेषतः |\nमनसैवेन्द्रियग्रामं विनियम्य समन्ततः ||", transliteration: "saṅkalpa-prabhavān kāmāns tyaktvā sarvān aśheṣhataḥ |\nmanasaivendriya-grāmaṁ viniyamya samantataḥ ||", meaning: "One should abandon, without exception, all material desires born of mental speculation and thus control all the senses on all sides by the mind.", lesson: "Root Cause. Desires start as thoughts (Sankalpa). Control your thoughts, and your actions will naturally follow." },
    { verse: "6.26", sanskrit: "यतो यतो निश्चरति मनश्चञ्चलमस्थिरम् |\nततस्ततो नियम्यैतदात्मन्येव वशं नयेत् ||", transliteration: "yato yato niśhcharati manaśh chañchalam asthiram |\ntatas tato niyamyaitad ātmanyeva vaśhaṁ nayet ||", meaning: "From wherever the mind wanders due to its flickering and unsteady nature, one must certainly withdraw it and bring it back under the control of the Self.", lesson: "Gentle Redirection. Meditation isn't having a blank mind; it's the *process* of catching your mind wandering and gently bringing it back." },
    { verse: "6.29", sanskrit: "सर्वभूतस्थमात्मानं सर्वभूतानि चात्मनि |\nईक्षते योगयुक्तात्मा सर्वत्र समदर्शनः ||", transliteration: "sarva-bhūta-stham ātmānaṁ sarva-bhūtāni chātmani |\nīkṣhate yoga-yuktātmā sarvatra sama-darśhanaḥ ||", meaning: "A true yogi observes Me in all beings and also sees every being in Me. Indeed, the self-realized person sees Me, the same Supreme Lord, everywhere.", lesson: "Universal Empathy. Real spirituality leads to seeing the same divine spark in every person, animal, and plant." },
    { verse: "6.30", sanskrit: "यो मां पश्यति सर्वत्र सर्वं च मयि पश्यति |\nतस्याहं न प्रणश्यामि स च मे न प्रणश्यति ||", transliteration: "yo māṁ paśhyati sarvatra sarvaṁ cha mayi paśhyati |\ntasyāhaṁ na praṇaśhyāmi sa cha me na praṇaśhyati ||", meaning: "For one who sees Me everywhere and sees everything in Me, I am never lost, nor is he ever lost to Me.", lesson: "Eternal Safety. When you are conscious of the Divine at all times, you are never alone or truly in danger." },
    { verse: "6.34", sanskrit: "चञ्चलं हि मनः कृष्ण प्रमाथि बलवद्दृढम् |\nतस्याहं निग्रहं मन्ये वायोरिव सुदुष्करम् ||", transliteration: "chañchalaṁ hi manaḥ kṛiṣhṇa pramāthi balavad dṛiḍham |\ntasyāhaṁ nigrahaṁ manye vāyor iva su-duṣhkaram ||", meaning: "The mind is restless, turbulent, strong, and obstinate, O Krishna. I find it as difficult to control as the wind.", lesson: "Honesty about the struggle. It is okay to find self-control hard; even the greatest warriors admitted it." },
    { verse: "6.35", sanskrit: "असंशयं महाबाहो मनो दुर्निग्रहं चलम् |\nअभ्यासेन तु कौन्तेय वैराग्येण च गृह्यते ||", transliteration: "asaṁśhayaṁ mahā-bāho mano durnigrahaṁ chalam |\nabhyāsena tu kaunteya vairāgyeṇa cha gṛihyate ||", meaning: "The Supreme Lord said: O mighty-armed son of Kunti, it is undoubtedly very difficult to curb the restless mind, but it is possible by constant practice and by detachment.", lesson: "The Two Tools. Practice (Abhyasa) and Detachment (Vairagya) are the only two wings you need to soar spiritually." },
    { verse: "6.40", sanskrit: "श्रीभगवानुवाच |\nपार्थ नैवेह नामुत्र विनाशस्तस्य विद्यते |\nन हि कल्याणकृत्कश्चिद्दुर्गतिं तात गच्छति ||", transliteration: "śhrī-bhagavān uvācha |\npārtha naiveha nāmutra vināśhas tasya vidyate |\nna hi kalyāṇa-kṛit kaśhchid durgatiṁ tāta gachchhati ||", meaning: "The Supreme Lord said: Son of Pritha, a transcendentalist engaged in auspicious activities does not meet with destruction either in this world or in the spiritual world; one who does good, My friend, is never overcome by evil.", lesson: "Spiritual Insurance. No effort toward goodness is ever wasted. Even if you fail today, your progress is permanently 'saved'." },
    { verse: "6.47", sanskrit: "योगिनामपि सर्वेषां मद्गतेनान्तरात्मना |\nश्रद्धावान्भजते यो मां स मे युक्ततमो मतः ||", transliteration: "yoginām api sarveṣhāṁ mad-gatenāntar-ātmanā |\nśhraddhāvān bhajate yo māṁ sa me yuktatamo mataḥ ||", meaning: "And of all yogis, the one with great faith who always abides in Me, thinks of Me within himself and renders transcendental loving service to Me—he is the most intimately united with Me in Yoga and is the highest of all. That is My opinion.", lesson: "Devotion is the Highest. All the physical postures and mental drills of yoga culminate in a heart full of love for the Truth." }
  ]
};