import { Chapter } from './types';

export const ch7: Chapter = {
  id: 7,
  name: "Paramahamsa Vijnana Yoga",
  meaning: "The Yoga of Supreme Knowledge",
  slokas_count: 30,
  summary: "Krishna describes His manifest and unmanifest nature, explaining that He is the essence of all things and the goal of all spiritual seeking.",
  themes: ["Divine Essence", "Modes of Nature", "Absolute Reality", "Faith"],
  featured_verse: "7.7",
  slokas: [
    { verse: "7.1", sanskrit: "श्रीभगवानुवाच |\nमय्यासक्तमनाः पार्थ योगं युञ्जन्मदाश्रयः |\nअसंशयं समग्रं मां यथा ज्ञास्यसि तच्छृणु ||", transliteration: "śhrī-bhagavān uvācha |\nmayy āsakta-manāḥ pārtha yogaṁ yuñjan mad-āśhrayaḥ |\nasaṁśhayaṁ samagraṁ māṁ yathā jñāsyasi tach chhṛiṇu ||", meaning: "The Supreme Lord said: Now hear, O son of Pritha, how by practicing yoga in full consciousness of Me, with mind attached to Me, you can know Me in full, free from doubt.", lesson: "Doubt-free Living. Sincere practice and focus on Truth eventually lead to a state of absolute certainty." },
    { verse: "7.3", sanskrit: "मनुष्याणां सहस्रेषु कश्चिद्यतति सिद्धये |\nयततामपि सिद्धानां कश्चिन्मां वेत्ति तत्त्वतः ||", transliteration: "manuṣhyāṇāṁ sahasreṣhu kaśhchid yatati siddhaye |\nyatatām api siddhānāṁ kaśhchin māṁ vetti tattvataḥ ||", meaning: "Out of many thousands among men, one may endeavor for perfection, and of those who have achieved perfection, hardly one knows Me in truth.", lesson: "The Rarity of Truth. Don't be discouraged if few follow this path. Real wisdom is a rare and precious achievement." },
    { verse: "7.4", sanskrit: "भूमिरापोऽनलो वायुः खं मनो बुद्धिरेव च |\nअहङ्कार इतीयं मे भिन्ना प्रकृतिरष्टधा ||", transliteration: "bhūmir-āpo ’nalo vāyuḥ khaṁ mano buddhir eva cha |\nahaṅkāra itīyaṁ me bhinnā prakṛitir aṣhṭadhā ||", meaning: "Earth, water, fire, air, ether, mind, intelligence and false ego—all together these eight constitute My separated material energies.", lesson: "Analyze your environment. Everything around you, including your own psychology, is part of a grand divine ecosystem." },
    { verse: "7.7", sanskrit: "मत्तः परतरं नान्यत्किञ्चिदस्ति धनञ्जय |\nमयि सर्वमिदं प्रोतं सूत्रे मणिगणा इव ||", transliteration: "mattaḥ perataraṁ nānyat kiñchid asti dhanañjaya |\nmayi sarvam idaṁ protaṁ sūtre maṇi-gaṇā iva ||", meaning: "There is nothing superior to Me, O Dhananjaya. Everything rests upon Me, like pearls strung on a thread.", lesson: "The Invisible Unity. God is the thread that holds all of existence together. Recognize the sacred in every pearl of experience." },
    { verse: "7.8", sanskrit: "रसोऽहमप्सु कौन्तेय प्रभास्मि शशिसूर्ययोः |\nप्रणवः सर्ववेदेषु शब्दः खे पौरुषं नृषु ||", transliteration: "raso ’ham apsu kaunteya prabhāsmi śhaśhi-sūryayoḥ |\npraṇavaḥ sarva-vedeṣhu śhabdaḥ khe pauruṣhaṁ nṛiṣhu ||", meaning: "O son of Kunti, I am the taste of water, the light of the sun and the moon, the syllable 'Om' in the Vedic mantras; I am the sound in ether and ability in man.", lesson: "Find God in the Mundane. You don't need a cathedral to find the Divine; He is in the light you see and the very water you drink." },
    { verse: "7.14", sanskrit: "दैवी ह्येषा गुणमयी मम माया दुरत्यया |\nमामेव ये प्रपद्यन्ते मायामेतां तरन्ति ते ||", transliteration: "daivī hy-eṣhā guṇamayī mama māyā duratyayā |\nmām eva ye prapadyante māyām etāṁ taranti te ||", meaning: "This divine energy of Mine, consisting of the three modes of material nature, is difficult to overcome. But those who have surrendered unto Me can easily cross over it.", lesson: "The Power of Surrender. Life's complexities (Maya) are too big for the ego. Trust the Source to navigate the storm." },
    { verse: "7.16", sanskrit: "चतुर्विधा भजन्ते मां जनाः सुकृतिनोऽर्जुन |\nआर्तो जिज्ञासुरर्थार्थी ज्ञानी च भरतर्षभ ||", transliteration: "chatur-vidhā bhajante māṁ janāḥ su-kṛitino ’rjuna |\nārto jijñāsur arthārthī jñānī cha bharatarṣhabha ||", meaning: "O best among the Bharatas, four kinds of pious men begin to render devotional service unto Me—the distressed, the desirer of wealth, the inquisitive, and he who is searching for knowledge of the Absolute.", lesson: "All Entries are Valid. Whether you seek God because of pain, need, curiosity, or a quest for truth, the important thing is that you have started." },
    { verse: "7.19", sanskrit: "बहूनां जन्मनामन्ते ज्ञानवान्मां प्रपद्यते |\nवासुदेवः सर्वमिति स महात्मा सुदुर्लभः ||", transliteration: "bahūnāṁ janmanām ante jñānavān māṁ prapadyate |\nvāsudevaḥ sarvam iti sa mahātmā su-durlabhaḥ ||", meaning: "After many births of spiritual practice, the wise surrender unto Me, realizing that everything is God. Such a great soul is very rare.", lesson: "Patience. The ultimate realization that 'God is All' is the work of many lifetimes; keep going." },
    { verse: "7.21", sanskrit: "यो यो यां यां तनुं भक्तः श्रद्धयार्चितुमिच्छति |\nतस्य तस्याचलां श्रद्धां तामेव विदधाम्यहम् ||", transliteration: "yo yo yāṁ yāṁ tanuṁ bhaktaḥ śhraddhayārchitum ichchhati |\ntasya tasyāchalāṁ śhraddhāṁ tām eva vidadhāmy aham ||", meaning: "I am in everyone's heart as the Supersoul. As soon as one desires to worship some demigod, I make his faith steady so that he can devote himself to that particular deity.", lesson: "Religious Tolerance. The Divine respects your individual path and supports your sincerity, wherever you point it." },
    { verse: "7.25", sanskrit: "नाहं प्रकाशः सर्वस्य योगमायासमावृतः |\nमूढोऽयं नाभिजानाति लोको मामजमव्ययम् ||", transliteration: "nāhaṁ prakāśhaḥ sarvasya yoga-māyā-samāvṛitaḥ |\nmūḍho ’yaṁ nābhijānāti loko mām ajam avyayam ||", meaning: "I am never manifest to the foolish and unintelligent. For them I am covered by My internal potency, and therefore they do not know that I am unborn and infallible.", lesson: "Spiritual Blindness. The Divine is 'hidden' in plain sight from those who only look with ego. Humility is the key to seeing clearly." },
    { verse: "7.28", sanskrit: "येषां त्वन्तगतं पापं जनानां पुण्यकर्मणाम् |\nते द्वन्द्वमोहनिर्मुक्ता भजन्ते मां दृढव्रताः ||", transliteration: "yeṣhāṁ tv anta-gataṁ pāpaṁ janānāṁ puṇya-karmaṇām |\nte dvandva-moha-nirmuktā bhajante māṁ dṛiḍha-vratāḥ ||", meaning: "Persons who have acted piously in previous lives and in this life and whose sinful actions are completely eradicated are freed from the dualities of delusion, and they engage themselves in My service with determination.", lesson: "Character Matters. Consistent good actions clear the 'fog' of confusion, allowing you to focus on your higher purpose." },
    { verse: "7.30", sanskrit: "साधिभूताधिदैवं मां साधियज्ञं च ये विदुः |\nप्रयाणकालेऽपि च मां ते विदुर्युक्तचेतसः ||", transliteration: "sādhibhūtādhidaivaṁ māṁ sādhiyajñaṁ cha ye viduḥ |\nprayāṇa-kāle ’pi cha māṁ te vidur yukta-chetasaḥ ||", meaning: "Those in full consciousness of Me, who know Me, the Supreme Lord, to be the governing principle of the material manifestation, of the demigods, and of all methods of sacrifice, can understand and know Me, the Supreme Lord, even at the time of death.", lesson: "Preparation for the End. A life of awareness ensures a fearless and conscious transition to the next state of being." }
  ]
};