import { Chapter } from './types';

export const ch8: Chapter = {
  id: 8,
  name: "Akshara-Parabrahman Yoga",
  meaning: "The Yoga of the Imperishable Absolute",
  slokas_count: 28,
  summary: "Krishna explains the nature of the Supreme Brahman and the soul, and reveals how one can attain liberation by remembering the Divine at the time of death.",
  themes: ["Final Thought", "Eternal Abode", "Cycle of Rebirth", "Brahman"],
  featured_verse: "8.6",
  slokas: [
    { verse: "8.1", sanskrit: "अर्जुन उवाच |\nकिं तद्ब्रह्म किमध्यात्मं किं कर्म पुरुषोत्तम |\nअधिभूतं च किं प्रोक्तमधिदैवं किमुच्यते ||", transliteration: "arjuna uvācha |\nkiṁ tad brahma kim adhyātmaṁ kiṁ karma puruṣhottama |\nadhibhūtaṁ cha kiṁ proktam adhidaivaṁ kim uchyate ||", meaning: "Arjuna inquired: O my Lord, O Supreme Person, what is Brahman? What is the self? What are fruitive activities? What is this material manifestation? And what are the demigods? Please explain this to me.", lesson: "Precision in Knowledge. Spiritual progress starts with defining our terms and understanding our relationship with reality." },
    { verse: "8.3", sanskrit: "श्रीभगवानुवाच |\nअक्षरं ब्रह्म परमं स्वभावोऽध्यात्ममुच्यते |\nभूतभावोद्भवकरो विसर्गः कर्मसंज्ञितः ||", transliteration: "śhrī-bhagavān uvācha |\nakṣharaṁ brahma paramaṁ swabhāvo ’dhyātmam uchyate |\nbhūta-bhāvodbhava-karo visargaḥ karma-sañjñitaḥ ||", meaning: "The Supreme Lord said: The indestructible, transcendental living entity is called Brahman, and its eternal nature is called adhyatma, the self. Action pertaining to the development of the material bodies of the living entities is called karma, or fruitive activities.", lesson: "Identity. You are the 'indestructible' element in your own story. Your habits and actions (karma) are what build your future circumstances." },
    { verse: "8.5", sanskrit: "अन्तकाले च मामेव स्मरन्मुक्त्वा कलेवरम् |\nयः प्रयाति स मद्भावं याति नास्त्यत्र संशयः ||", transliteration: "anta-kāle cha mām eva smaran muktvā kalevaram |\nyaḥ prayāti sa mad-bhāvaṁ yāti nāstyatra sanśhayaḥ ||", meaning: "And whoever, at the time of death, quits his body, remembering Me alone, at once attains My nature. Of this there is no doubt.", lesson: "Final Focus. Our life's meditation prepares us for our final exit. What we value most during life will be our last thought." },
    { verse: "8.6", sanskrit: "यं यं वापि स्मरन्भावं त्यजत्यन्ते कलेवरम् |\nतं तमेवैति कौन्तेय सदा तद्भावभावितः ||", transliteration: "yaṁ yaṁ vāpi smaran bhāvaṁ tyajaty ante kalevaram |\ntaṁ tam evaiti kaunteya sadā tad-bhāva-bhāvitaḥ ||", meaning: "Whatever state of being one remembers when quitting the body, that state one will attain without fail, because of being absorbed in it.", lesson: "The Law of Attraction. We become what we dwell upon. Use your daily life to cultivate high-quality thoughts so that they become your natural default." },
    { verse: "8.7", sanskrit: "तस्मात्सर्वेषु कालेषु मामनुस्मर युध्य च |\nमय्यर्पितमनोबुद्धिर्मामेवैष्यस्यसंशयः ||", transliteration: "tasmāt sarveṣhu kāleṣhu mām anusmara yudhya cha |\nmayy arpita-mano-buddhir mām evaiṣhyasy asaṁśhayaḥ ||", meaning: "Therefore, Arjuna, you should always think of Me and at the same time carry out your prescribed duty of fighting. With your activities dedicated to Me and your mind and intelligence fixed on Me, you will attain Me without doubt.", lesson: "Spirituality + Action. Don't stop working to be spiritual. Carry your spiritual focus *into* your daily battles." },
    { verse: "8.14", sanskrit: "अनन्यचेताः सततं यो मां स्मरति नित्यशः |\nतस्याहं सुलभः पार्थ नित्ययुक्तस्य योगिनः ||", transliteration: "ananya-chetāḥ satataṁ yo māṁ smarati nityaśhaḥ |\ntasyāhaṁ su-labhaḥ pārtha nitya-yuktasya yoginaḥ ||", meaning: "For one who always remembers Me without deviation, I am easy to obtain, O son of Pritha, because of his constant engagement in devotional service.", lesson: "The Easy Path. Consistency is the secret. Small, steady reminders of Truth are more powerful than occasional grand gestures." },
    { verse: "8.15", sanskrit: "मामुपेत्य पुनर्जन्म दुःखालयमशाश्वतम् |\nनाप्नुवन्ति महात्मानः संसिद्धिं परमां गताः ||", transliteration: "mām upetya punar janma duḥkhālayam aśhāśhvatam |\nnāpnuvanti mahātmānaḥ saṁsiddhiṁ paramāṁ gatāḥ ||", meaning: "After attaining Me, the great souls, who are yogis in devotion, never return to this temporary world, which is full of miseries, because they have attained the highest perfection.", lesson: "Transcending Pain. The ultimate goal is to exit the cycle of stress and struggle, reaching a state of permanent peace." },
    { verse: "8.20", sanskrit: "परस्तस्मात्तु भावोऽन्योऽव्यक्तोऽव्यक्तात्सनातनः |\nयः स सर्वेषु भूतेषु नश्यत्सु न विनश्यति ||", transliteration: "paras tasmāt tu bhāvo ’nyo ’vyakto ’vyaktāt sanātanaḥ |\nyaḥ sa sarveṣhu bhūteṣhu naśhyatsu na vinaśhyati ||", meaning: "Yet there is another unmanifest nature, which is eternal and is transcendental to this manifested and unmanifested matter. It is supreme and is never annihilated. When all in this world is annihilated, that part remains as it is.", lesson: "The Unchanging Reality. Beneath all the noise and change of the world, there is a foundation of peace that never disappears. Learn to stand on that ground." },
    { verse: "8.21", sanskrit: "अव्यक्तोऽक्षर इत्युक्तस्तमाहुः परमां गतिम् |\nयं प्राप्य न निवर्तन्ते तद्धाम परमं मम ||", transliteration: "avyakto ’kṣhara ity uktas tam āhuḥ paramāṁ gatim |\nyaṁ prāpya na nivartante tad dhāma paramaṁ mama ||", meaning: "That which the Vedantists describe as unmanifest and infallible, which is known as the supreme destination, that place from which, having attained it, one never returns—that is My supreme abode.", lesson: "The Home of the Soul. Aim for the highest possible state of consciousness. It is your true home." },
    { verse: "8.28", sanskrit: "वेदेषु यज्ञेषु तपःसु चैव\nदानेषु यत्पुण्यफलं प्रदिष्टम् |\nअत्येति तत्सर्वमिदं विदित्वा\nयोगी परं स्थानमुपैति चाद्यम् ||", transliteration: "vedeṣhu yajñeṣhu tapaḥsu chaiva\ndāneṣhu yat puṇya-phalaṁ pradiṣhṭam |\natyeti tat sarvam idaṁ viditvā\nyogī paraṁ sthānam upaiti chādyam ||", meaning: "A person who accepts the path of devotional service is not bereft of the results derived from studying the Vedas, performing sacrifices, giving in charity or pursuing philosophical activities. Simply by performing devotional service, he attains all these, and at the end he reaches the supreme eternal abode.", lesson: "The Ultimate 'All-in-One'. Living with a heart full of devotion covers all other spiritual requirements. It is the master key to wisdom." }
  ]
};