import { Chapter } from './types';

export const ch9: Chapter = {
  id: 9,
  name: "Raja-Vidya-Guhya Yoga",
  meaning: "The Yoga of Royal Knowledge",
  slokas_count: 34,
  summary: "Krishna reveals the most confidential knowledge: His immanence and transcendence, and the simplicity of pure devotion.",
  themes: ["Divine Secret", "Devotional Service", "Divine Protection", "Inclusivity"],
  featured_verse: "9.22",
  slokas: [
    { verse: "9.1", sanskrit: "श्रीभगवानुवाच |\nइदं तु ते गुह्यतमं प्रवक्ष्याम्यनसूयवे |\nज्ञानं विज्ञानसहितं यज्ज्ञात्वा मोक्ष्यसेऽशुभात् ||", transliteration: "śhrī-bhagavān uvācha |\nidaṁ tu te guhyatamaṁ pravakṣhyāmy anasūyave |\njñānaṁ vijñāna-sahitaṁ yaj jñātvā mokṣhyase ’śhubhāt ||", meaning: "The Supreme Lord said: My dear Arjuna, because you are never envious of Me, I shall impart to you this most secret wisdom and realization, knowing which you shall be relieved of the miseries of material existence.", lesson: "Envy blocks learning. A non-judgmental and humble heart is the perfect vessel for the highest secrets of life." },
    { verse: "9.2", sanskrit: "राजविद्या राजगुह्यं पवित्रमिदमुत्तमम् |\nप्रत्यक्षावगमं धर्म्यं सुसुखं कर्तुमव्ययम् ||", transliteration: "rāja-vidyā rāja-guhyaṁ pavitram idam uttamam |\npratyakṣhāvagamaṁ dharmyaṁ su-sukham kartu-mavyayam ||", meaning: "This knowledge is the king of education, the most secret of all secrets. It is the purest knowledge, and because it gives direct perception of the self by realization, it is the perfection of religion. It is everlasting, and it is joyfully performed.", lesson: "The Joy of Truth. Real spiritual knowledge doesn't feel like a chore; it is an exhilarating and joyous discovery." },
    { verse: "9.4", sanskrit: "मया ततमिदं सर्वं जगदव्यक्तमूर्तिना |\nमत्स्थानि सर्वभूताणि न चाहं तेष्ववस्थितः ||", transliteration: "mayā tatam idaṁ sarvaṁ jagad avyakta-mūrtinā |\nmat-sthāni sarva-bhūtāṇi na chāhaṁ teṣhv avasthitaḥ ||", meaning: "By Me, in My unmanifested form, this entire universe is pervaded. All beings are in Me, but I am not in them.", lesson: "Transcendent Support. The Divine supports the world like an ocean supports waves—always present, but never fully contained by them." },
    { verse: "9.13", sanskrit: "महात्मानस्तु मां पार्थ दैवीं प्रकृतिमाश्रिताः |\nभजन्त्यनन्यमनसो ज्ञात्वा भूतादिमव्ययम् ||", transliteration: "mahātmānas tu māṁ pārtha daivīṁ prakṛitim āśhritāḥ |\nbhajanty ananya-manaso jñātvā bhūtādim avyayam ||", meaning: "O son of Pritha, those who are not deluded, the great souls, are under the protection of the divine nature. They are fully engaged in devotional service because they know Me as the Supreme Divine Personality, original and inexhaustible.", lesson: "Choose your 'Nature'. Aim to live under the guidance of your higher, divine nature rather than your base instincts." },
    { verse: "9.22", sanskrit: "अनन्याश्चिन्तयन्तो मां ये जनाः पर्युपासते |\nतेषां नित्याभियुक्तानां योगक्षेमं वहाम्यहम् ||", transliteration: "ananyāśh chintayanto māṁ ye janāḥ paryupāsate |\nteṣhāṁ nityābhiyuktānāṁ yoga-kṣhemaṁ vahāmyaham ||", meaning: "Those who always worship Me with exclusive devotion, meditating on My transcendental form—to them I carry what they lack and preserve what they have.", lesson: "Absolute Trust (Yoga-Kshema). When your heart is truly surrendered, the universe provides for your needs and protects your progress." },
    { verse: "9.26", sanskrit: "पत्रं पुष्पं फलं तोयं यो मे भक्त्या प्रयच्छति |\nतदहं भक्त्युपहृतमश्नामि प्रयतात्मनः ||", transliteration: "patraṁ puṣhpaṁ phalaṁ toyaṁ yo me bhaktyā prayachchhati |\ntad ahaṁ bhakty-upahṛitam aśhnāmi prayatātmanaḥ ||", meaning: "If one offers to Me with devotion a leaf, a flower, a fruit, or even water, I accept it, for it was offered with love by a pure heart.", lesson: "Intention over Value. The smallest act of kindness, if sincere, is immensely valuable in the eyes of God." },
    { verse: "9.27", sanskrit: "यत्करोषि यदश्नासि यज्जुहोषि ददासि यत् |\nयत्तपस्यसि कौन्तेय तत्कुरुष्व मदर्पणम् ||", transliteration: "yat karoṣhi yad aśhnāsi yaj juhoṣhi dadāsi yat |\nyat tapasyasi kaunteya tat kuruṣhva mad-arpaṇam ||", meaning: "Whatever you do, whatever you eat, whatever you offer or give away, and whatever austerities you perform—do that, O son of Kunti, as an offering to Me.", lesson: "Spirituality in All Actions. You don't need a temple to be spiritual; every mundane act can be a prayer if performed for a higher cause." },
    { verse: "9.29", sanskrit: "समोऽहं सर्वभूतेषु न मे द्वेष्योऽस्ति न प्रियः |\nये भजन्ति तु मां भक्त्या मयि ते तेषु चाप्यहम् ||", transliteration: "samo ’haṁ sarva-bhūteṣhu na me dveṣhyo ’sti na priyaḥ |\nye bhajanti tu māṁ bhaktyā mayi te teṣhu chāpy aham ||", meaning: "I envy no one, nor am I partial to anyone. I am equal to all. But whoever renders service unto Me in devotion is a friend, is in Me, and I am also a friend to him.", lesson: "The Open Door. The Divine is like the sun—shining on everyone equally. You just have to step out of the shadow of your ego to feel the warmth." },
    { verse: "9.30", sanskrit: "अपि चेत्सुदुराचारो भजते मामनन्यभाक् |\nसाधुरेव स मन्तव्यः सम्यग्व्यवसितो हि सः ||", transliteration: "api chet su-durāchāro bhajate mām ananya-bhāk |\nsādhur eva sa mantavyaḥ samyag vyavasito hi saḥ ||", meaning: "Even if one commits the most abominable action, if he is engaged in devotional service he is to be considered saintly because he is properly situated in his determination.", lesson: "Redemption. Your past does not define you. A strong resolution to change is the beginning of saintliness." },
    { verse: "9.31", sanskrit: "क्षिप्रं भवति धर्मात्मा शश्वच्छान्तिं निगच्छति |\nकौन्तेय प्रतिजानीहि न मे भक्तः प्रणश्यति ||", transliteration: "kṣhipraṁ bhavati dharmātmā śhaśhvach-chhāntiṁ nigachchhati |\nkaunteya pratijānīhi na me bhaktaḥ praṇaśhyati ||", meaning: "He quickly becomes righteous and attains lasting peace. O son of Kunti, declare it boldly that My devotee never perishes.", lesson: "Divine Protection. Sincere effort on the spiritual path grants you a permanent safety net. You can stumble, but you will not be destroyed." },
    { verse: "9.32", sanskrit: "मां हि पार्थ व्यपाश्रित्य येऽपि स्युः पापयोनयः |\nस्त्रियो वैश्यास्तथा शूद्रास्तेऽपि यान्ति परां गतिम् ||", transliteration: "māṁ hi pārtha vyapāśhritya ye ’pi syuḥ pāpa-yonayaḥ |\nstriyo vaiśhyās tathā śhūdrās te ’pi yānti parāṁ gatim ||", meaning: "O son of Pritha, those who take shelter in Me, though they be of lower birth—women, vaishyas (merchants) and shudras (workers)—can attain the supreme destination.", lesson: "Spiritual Equality. The Divine does not care about your gender, social status, or background. The only qualification is a sincere heart." },
    { verse: "9.34", sanskrit: "मन्मना भव मद्भक्तो मद्याजी मां नमस्कुरु |\nमामेवैष्यसि युक्त्वैवमात्मानं मत्परायणः ||", transliteration: "man-manā bhava mad-bhakto mad-yājī māṁ namaskuru |\nmām evaiṣhyasi yuktvaivam ātmānaṁ mat-parāyaṇaḥ ||", meaning: "Engage your mind always in thinking of Me, become My devotee, offer obeisances to Me and worship Me. Being completely absorbed in Me, surely you will come to Me.", lesson: "The Summary. Make 'Truth' your constant focus, your highest goal, and your deepest love." }
  ]
};